### ISSUE TITLE
App is not syncing all contacts

### ISSUE THREAD

**Issue by kpiq** [klinker-apps/messenger-issues#105]
Folks,

The app is not syncing all contacts from my smartphone to Messenger.   Out of more than 1200 it's only registering about 630.

Also, how about doing some Google account integration so that you don't actually have to keep my contacts in your database, just access them from my Google account?

**Comment by kpiq** [comment]
My account in Messenger is kpiqpr@gmail.com

**Comment by klinker24** [comment]
Only contacts with a "mobile" number will get uploaded, this is not something that we will change.

Google account integration isn't planned. We use a your password pas part of the end to end encryption key, which is why we do not have Google account login to begin with. Adding a Google account just for contacts adds unnecessary complexity and is not something we will be doing.

If the contact upload issue dies not have to do with the mobile only numbers, feel free to reopen and provide additional information
