### ISSUE TITLE
Delayed sending of SMS

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#114]
**Implementation notes:**

I don't want to make this a settings option. Instead, maybe long clicking the send button would be a good way to implement it. Could long click, then dragging upwards would increase the timeout.

This would create a nice clean feature that didn't require a setting.Will have to consider visibility of the feature if this is how it is implemented though, something to alert the user to its existence.

**Comment by klinker41** [comment]
This is also very easy to implement in the sms/mms sending library, so that wouldn't be an issue.

**Comment by klinker41** [comment]
One thing to keep in mind for this, the people who want it want to be able to use it because they are drunk and want to cancel the message after they push send. Having a long click on the send button to activate it won't really accomplish this for the majority of use cases, so I'm not sure it's a good solution.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/f781cfc3585ec5c9f7dbf1ec0d6ec9a807b163a7

It is toggled off, user's can't access it yet.

I went with a more normal settings approach. Nav Drawer -> Advanced Features -> Delayed Sending
