### ISSUE TITLE
SIM stamp on messages

### ISSUE THREAD

**Issue by tinujoseph987** [klinker-apps/messenger-issues#137]
**Request:**

Display what SIM card was used for incoming and outgoing messages, on a dual SIM device.

**Implementation notes:**

We would need a new column on the `message` table: `sim_slot`. This column would really just like on the primary device, since other devices don't know about SIM cards. Whenever a message is received, it will have an address on it, we should use this address to match it with available SIM cards and write the sim slot to that column.

For sent messages, when possible, we should write to the same column. 

To display on the UI, they should be shown next to the timestamp.

**Comment by klinker24** [comment]
In the future, as I posted with my last comment, please follow the requested template for submitting issues.

I have stated that this is something I would like to do: https://plus.google.com/+GabrielKomarnickiAU/posts/LpdXFKrNuNJ

**Comment by klinker24** [comment]
This is now done.

Any messages received will get a SIM stamp next to the timestamp to tell what SIM card it was received on.

Any messages sent from the following methods will get a SIM stamp of the number used to send the message:

- Message list
- Notification reply services/activities
- Android auto
- Firebase (for sending from tablets and web)

SIM stamps could not be written from scheduled messages or the headless sending service, because of some issues with conversation and finding it before sending the message.
