### ISSUE TITLE
Add ability for Android to speak messages to you

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#179]
**Request:**

It would be cool if Android could speak messages to you from a long press message action.

**Implementation:**

This should be very easy. Just adding a button to the long click menu, then telling Android to speak to you.

Android can provide speech with the TTS services.

**Comment by uudruid74** [comment]
Actually, I'd like to request that this be an option that can be turned on all the time.  Those that are sight impaired won't want to find a button to press.  Most people can read the message themselves in the time it takes to push a button.  And I want it in my car so I can make the notification a heads-up on my Android head unit ... but having it read over the car speakers would be much safer than looking down at the dash.  I would only want it automatic in the car, not the phone, so as long as the setting was per device this would be WONDERFUL

**Comment by klinker41** [comment]
Accessibility services already seem like they handle this... It will read textviews to you automatically, so I'm not sure what the benefit is of us adding this as well.

**Comment by uudruid74** [comment]
I don't see it ... likely ROM specific?

**Comment by uudruid74** [comment]
and I don't use android auto. .. its a full android os

**Comment by madlovin** [comment]
If you use the, "OK Google, read text" command, it will read the texts.  You can also start this by holding the home button on most phones, or pressing a microphone icon on the screen to activate the process as well.  If you are on bluetooth, your device most likely has a button (such as a voice dial button) to initiate the "OK Google" portion.  I use this regularly while in the truck or while on the motorcycle, and it works no worse than standard Google services.

**Comment by uudruid74** [comment]
First, I want to know that the text came in.   My phone is next to me, my Android head unit is blasting music much too loud to hear the alert, but here come Pulse to save the day.  Since my head unit runs Android (Lollipop actually) I can install Pulse on it and use the phone's hotspot to transfer the messages to the car.  I'll then get a heads-up on the car and I'll get a notification as if the SMS came into the head unit (which does not have a SIM).

Is it too much to ask to have a switch that sends all the messages that come in the headunit through the standard Text-to-Speech system so I don't have to take my eyes off the road?   That's a single function call to read the text and stops me from fiddling with stuff while I'm driving.

Holding the Home button on the head unit does not pull up Google Voice.  I could assign a steering wheel button to such a command, but I don't have steering wheel buttons (yet).  Not to mention the RAM required to load the Google App (not sure if it even reads texts without the Assistant which isn't available on Lollipop) and the task switches and all that for something that would be way easier in Pulse.

I'm sure I can find something to read my notifications out loud via the Accessibility API, but at that point, is it worth installing yet another program?  If Pulse won't do it, maybe I should write an app that reads the notifications on the phone and sends them via the hotspot (no server or Internet required) to tiny service on the head unit to read.

**Comment by cojaksoccer06** [comment]
My car notifies me if a message is received via bluetooth and presents me with an option to have the system read it to me by pushing a button on the steering wheel.
This feature has worked with every Android SMS app I've tried, except Pulse.
I *don't* have Android Auto or anything that fancy; just the basic head unit in the 2017 Nissan Rogue.

I would appreciate this feature being enabled.

**Comment by klinker41** [comment]
My car does read them to me and I hate it, all I want is a way to turn it off... Pulse doesn't do anything that would be messing with the car's ability to read messages though that I can't think of (I don't even sure that would be possible as all of that works through Bluetooth with the [Message Access Profile](https://en.wikipedia.org/wiki/List_of_Bluetooth_profiles#Message_Access_Profile_(MAP))).

**Comment by uudruid74** [comment]
First, most people don't have Message Access Profile.  Its more common to just use the Media profile, so if the phone itself doesn't read the message via Google's text-to-speech API, it's not going to get done.  This also works via good ol' AUX cable.

To stop Message Access Profile, you should be able to open the bluetooth settings for your car and you'll see options for Media, Phone, Contacts, and I'm guessing Messages.  Just uncheck the box to deny.

**Comment by klinker24** [comment]
This is done, as described in the initial request. Long click a message to be presented with the option to have Android speak it to you.

https://github.com/klinker41/messenger/commit/de60219313f8602e4eb77e4cedfdba23158e4b07
