### ISSUE TITLE
Dialogs don't display

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#19]
**Device with issue:** Mac Pro running OSX 10.11.6 and Chrome v53
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.0.180
**Steps to reproduce:**
1. Go into the blacklist section of the chrome app
2. Click on a blacklist item
3. A dialog would be shown here on the web version asking if it is ok to delete the item, but it is not shown here

**Additional information:**

Chrome apps restrict dialogs being shown. This also happens in other sections such as deleting a scheduled message, deleting a conversation, or blacklisting a contact.

**Possible solution:**

We'll need to build the dialogs directly into the HTML instead, which will be better for uniform feel anyways.

**Comment by klinker24** [comment]
Javascript `confirm` dialogs are used in the following places:

- blacklist: "do you want to delete?"
- message list: "are you sure you want to blacklist?"
- message list: "are you sure you want to delete?"
- message list: "are you sure you want to archive?"
- message list: "are you sure you want to move this back to the inbox?"
- message list: "are you sure you want to send this mms?"
- scheduled messages: "are you sure you want to delete?"


For fixing this, there are some places I just want to remove the alerts, and some places I want to add a custom confirmation dialog (similar to the add scheduled message or blacklist fab action).

Custom dialogs:
- [ ] blacklist deletion
- [ ] conversation deletion

Remove confirmation:
- [ ] archive and blacklist from the message list (since neither of these are actually destructive)
- [ ] sending MMS messages
- [ ] deleting scheduled messages (since this is already in a dialog "edit" view)

**Comment by klinker24** [comment]
Here is the method definition for the custom confirmation dialog: https://github.com/klinker41/messenger-web/commit/aacef20466e5270edbd6929a72eb768205d679e9
