### ISSUE TITLE
Switch conversations by swipping left or right

### ISSUE THREAD

**Issue by vincentvidal** [klinker-apps/messenger-issues#190]
**Request:**

One interesting feature of EvolveSMS was the possibility to switch from one conversation to another by swipping left or right. Why not implementing this feature in Pulse?

**NB:**

Many thanks for the tremendous work you make on this app, and congrats for the result: probably the best SMS app I've tested ;-)

**Comment by klinker24** [comment]
While this was an awesome feature for evolve, the whole app was built around it, and it had a number of problems with performance, memory, speed, startup time

Because of these drawbacks, it won't be coming to this app, and those issues were one of the main reasons we didn't want to move forward with building the text anywhere functionality into evolve. We needed something cleaner, and faster, that worked for everyone
