### ISSUE TITLE
Global Setting for Notification LED Color

### ISSUE THREAD

**Issue by hsanchez94** [klinker-apps/messenger-issues#215]
Nexus 6P Android 7.1.1

I wanted to ask if it'd be possible to implement a global setting for the color of the notification LED, unless there's already a way of doing it that I'm not aware of.

Basically, I'd like to be able to change the color of my notification LED so that is it BLUE (or whatever color) for any sms message received through Pulse without having to go through each conversation list to change it.

**Comment by klinker24** [comment]
So the reason that I have avoided a global setting, for this, in the past, is that LEDs can be very inconsistent between different devices/manufacturers. If you select an invalid color (which the app has no way of knowing), it can completely remove the LED from the notification and a user would not understand why.

Obviously this is still a problem for doing at the conversation level as well, but, in this case, if you change something and it gets messed up, it would only be the single conversation, which could be easier for the user to diagnose. 

By using the `DEFAULT` value at the global level, the app ensures that it is able to handle things correctly, for the most amount of time.

Because of these hardware limitations, I don't think that this is something I am going to add at this time
