### ISSUE TITLE
Custom vibrations per contact

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#252]
**Request:**

Some users have asked if we could get custom vibration patterns per contact, since we can select them on a global level.

**Answer:**

This is not currently planned. There are only so many options for vibration patterns, where something like the LED can have almost unlimited options. Because of this limitation, I don't see myself adding custom vibrations per contact. This is much more suited for a global setting then a contact setting.

**Comment by DragonMama** [comment]
HandCent and Textra offer this. As someone who is hard-of-hearing, I depend on this feature to know which family member is trying to reach me. As much as I would like to be able to check/reply to messages on my laptop or tablet instead of switching to my phone, this is a must-have accessibility feature and I cannot switch to your app (which I would otherwise happily pay for) for this reason. Please look at how your competition is doing this and reconsider.
