### ISSUE TITLE
Individual conversation notification icons? 

### ISSUE THREAD

**Issue by wizard7926** [klinker-apps/messenger-issues#279]
This is a feature of Textra, so I'm not sure if it's possible using the stock messaging system. Each conversation would have its own notification, not grouped in as one lump notification. Additionally, each conversation would be able to have its own colored notification icon, which was really helpful in determining who had texted at a glance. It's one of the few things I still miss from Textra - I'm a full Pulse convert (and working on my brother)! Thanks!

**Comment by klinker24** [comment]
I talk a bit about the colored notification icons here: https://github.com/klinker-apps/messenger-issues/issues/161

In short, this is not something that should be done.

---

As for the individual notifications for each conversation, this is something that Google urges developers to avoid. If a notification is for the same types of content, then they only want you to provide a single notification. With Android Nougat, the grouped notifications have been vastly improved and each item in the group gets an individual notification entry: http://www.androidcentral.com/android-70-better-and-more-interactive-notifications

Since this goes against what Google wants in their guidelines though, individual notifications will not be coming to older versions of Android, sorry

**Comment by wizard7926** [comment]
Thanks for the super quick reply and insight!
