### ISSUE TITLE
Timestamps don't update from "Now" to actual timestamp

### ISSUE THREAD

**Issue by jeffshaver** [klinker-apps/messenger-issues#306]
**Device with issue:** Pixel XL on Android 7.1.2
**Primary device:** Pixel XL on Android 7.1.2
**App version:** 2.2.4.1111
**Steps to reproduce:**

1. Click on a message to show the timestamp
2. Wait and watch it never change

**Additional information:**

I expected the timestamp to change from "Now" to like the time it was sent after a few minutes. I had to back out of the conversation and then go back into the conversation and re-tap on the message to see the timstamp.

**Possible solution:**

No Idea

**Comment by klinker24** [comment]
If you just scroll the view off the screen and back on, it would update. It isn't going to do it automatically though, sorry. I don't think this will change

**Comment by zlrenner** [comment]
@klinker24 Disappointed this is wontfix. I'm often confused by this as well.

If live update isn't feasible to implement, I might suggest an option to always display datetimes instead of  "now".

**Comment by jeffshaver** [comment]
I think always displaying the timestamp is a good idea instead of having it saying "now"

**Comment by klinker41** [comment]
Thanks for the suggestions, we'll keep them in mind for the future.

**Comment by krayakin** [comment]
What about after the screen unlocks? This is rather confusing to the user after unlocking after a period.

**Comment by rndstr** [comment]
I was just about to create the same issue.

This is really annoying when you have `Timestamp Every Message` enabled. I'm texting back and forth and the timestamps stay on `Now` the whole period.

To fix this, I either need to
- toggle timestamps off and on again on every message after a while (by tapping it)
- go back to conversation list and re-enter
- scroll up and down

all of these are annoying because i never know whether the 'Now' is ready to update or not. So I'm constantly doing any of these as a first reaction if i go back to text more messages and I see some 'Now's but rarely they actually update because they are still within that window.
