### ISSUE TITLE
No global color for per conversation color

### ISSUE THREAD

**Issue by Jensen95** [klinker-apps/messenger-issues#317]
**Device with issue:** LG G5
**Primary device:** LG G5
**App version:** 2.2.8.1154
**Steps to reproduce:**

1. Go to 'Global settings'
2. Select 'Theme Color' and choose 'Set color per conversation'
3. Can't choose the global color anywhere

**Additional information:**

I don't know if it's intended or not, but I think it should be possible to choose the global color when having selected per conversation color. As it is now, it's only possible to change the color on the messages overview by selecting a specific color.

**Possible solution:**

Either add a new menu option when 'Set color per conversation' is selected or make a modal asking for the global color when it's selected.

**Comment by klinker24** [comment]
Sorry, this is working as intended. At this time, this is a simplification measure for both users getting into the app, and the development side. 

It may change in the future, but at this point, this is how I want it to work.

**Comment by wizard7926** [comment]
Just chiming in on this - I find that for some reason, Pulse will choose a bright yellow/orange (quite unreadable) color as the default, so I have to change a lot more conversations than I'd like because of that. I think it makes a lot of sense to have a default color with the ability to change whichever conversations need a different option.
