### ISSUE TITLE
Slow response times on update actions from server

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#32]
**Device with issue:** Server 
**Server Deploy Version:** 54

As seen through `Rollbar` and `New Relic`, some of the `UPDATE` routes are taking extra computing time. 

This is almost certainly due to using `ActionRecord` at those points, instead of raw SQL. As with inserting conversations and messages, turning these from `ActionRecord` requests to SQL commands would be pretty trivial and would vastly increase the performance of these endpoints.

**Additional Information** 

When I am talking about performance here, the app currently does not have any performance issues. Our responses our almost always < 100 ms which is excellent for an API. As we grow in users though, an extra 50 - 100 ms could cause a huge load on the server, which is something easily optimized.

**Comment by klinker41** [comment]
Could be that we're seeing these slow responses when a user has a lot of conversations or messages, since update has to first search through them. Raw SQL wouldn't help much with this, but it wouldn't hurt to experiment. Usually updates should be slower than reads, so might just be naturally slower.

**Comment by klinker41** [comment]
@klinker24 should we close this one now or keep monitoring it for a while longer?

**Comment by klinker24** [comment]
close her down. Server is doing great handling everything
