### ISSUE TITLE
Wear fails to send reply

### ISSUE THREAD

**Issue by joshuamking** [klinker-apps/messenger-issues#348]
**Device with issue:** Android Wear Huawei Watch 1
**Primary device:** Pixel XL on Android O and before on 7.1.2
**App version:** 2.3.4.1239
**Steps to reproduce:**

1. Open Android Wear app
2. Open a conversation
3. Tap reply
4. Type message
5. Tap send

**Additional information:**

Wear device is can be connected via Bluetooth or WiFi and it doesn't matter.

**Comment by klinker24** [comment]
Since you are on the beta version of Android, I am going to close this, I don't think we should expect everything to work perfectly, especially around networking, with all their changes to background services.

I would just restart the phone first. If that doesn't work, there is a "refresh account" option under the "my account" section of your phone. I have found that sometimes my phone on Android O will just stop receiving push notifications until it is restarted, which would prevent your messages from getting sent, from the watch.

**Comment by joshuamking** [comment]
Okay, understandable, however as I mentioned above, it was happening on 7.1.2 non-beta before I updated to O.
