### ISSUE TITLE
Receiving Messages Very Late at Random

### ISSUE THREAD

**Issue by alanwhiteman** [klinker-apps/messenger-issues#352]
- [X ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Android Phone
**Primary device:** Moto G 3rd - Android 6.0.1
**App version:** 2.3.4.1239
**Steps to reproduce:** None

I just switched to Pulse SMS and replaced my stock messaging app. All the features seem to work perfectly fine. However, there seems to be a strange anomaly: I'm getting random past messages. I received a message this morning at 5am that was sent two days ago. And I just received a string of messages that was sent to me about 12 hours ago.

I wonder if this has to do with the web sync. I have not created a "Text from any device" account.

**Comment by klinker24** [comment]
No, it wouldn't have anything to do with syncing on the web. Everything is controlled by your phone, since it is your connection to the carrier. 

Admittedly, I don't have much control here. Android sends out a broadcast to any apps that are listening, when it receives the message. Pulse doesn't actually do the receiving though, so I cannot imagine this being on my end..

**Comment by alanwhiteman** [comment]
It may very well be the phone carrier.
