### ISSUE TITLE
Group message contact lists display incorrectly when contact names contain commas

### ISSUE THREAD

**Issue by Wilson421** [klinker-apps/messenger-issues#356]
**Device with issue:** Pixel XL on Android 7.1.2
**Primary device:** Pixel XL on Android 7.1.2
**App version:** 2.3.4.1239
**Steps to reproduce:**

1. Send or receive group MMS with one or more contacts whose names contain a suffix in your contact list, e.g. "Wilson Cook, III" (me) and "Wilson Cook, IV" (my son).
2. Open the conversation, click the person icon next to the names
3. The list of contact shows the correct numbers, but names are shifted down with suffixes "III" and "IV" acting as contact names

**Additional information:**
The app does not handle commas received from Contacts properly. Each name in the list is delimited by commas, and since name suffixes are separated by commas as well, it assumes the suffix is its own name.

**Possible solution:**
Use a different delimiter like a semicolon in the contact list, use angle brackets around names like email programs do, or use a data structure or some other algorithmic devilry to handle lists of contacts.

**Comment by klinker24** [comment]
Thanks for the report. Right now, I am just going to go ahead and remove the "," from the contact names. There are some other ways to solve this, but the problem is deeper than what is on the surface, unfortunately. So we will just work around it right now. 

The names would be "Wilson Cook III" and "Wilson Cook IV" now. This will at least make it so you get the correct contacts, in the contacts dialog.
