### ISSUE TITLE
Dual Sim support for separate personal and work SMS

### ISSUE THREAD

**Issue by HonestJohn61** [klinker-apps/messenger-issues#368]
Very interested in Pulse, but I wanted to ask about a possible development for dual sim support.

I have a second SIM in my phone specifically for work SMS, and I want to keep work texts separate from my personal SMS. I also want the PCs in my business (used by me and others) to link to the work texts, but not have access to my personal texts.

As I understand it, Pulse works around one primary phone with one collection of SMS messages – so I recognise that this would be a fundamental change to the way it operates. I know that dual sim is also pretty niche – and whilst some dual sim folks do what I do, others want a second sim for personal use to achieve better coverage or operate in different countries, so one collection makes perfect sense for them. But, if Pulse did support separate personal and work SMS collections in this way, with separate web access to each collection, it would be really helpful (UK English for TOTALLY AWESOME).

Thanks!

**Comment by klinker24** [comment]
It is an interesting suggestion, but like you said, a fundamental change from the way pulse is designed. 

At this point, that isn't something that I am going to be willing to do. 

I had never thought about this as an application of dual SIM, I had only ever considered your other case, since most works seem to provide a completely separate phone for their usage.

If anything changes in the future, I will reopen this and definitely discuss it further, sorry about that
