### ISSUE TITLE
Edit participants in MMS conversation

### ISSUE THREAD

**Issue by Yozakgg** [klinker-apps/messenger-issues#374]
I am aware that MMS doesn't support adding participants, but can you implement something like in Google's messaging app, where it creates a new conversation with the added contacts.
http://i.imgur.com/oo0lo0i.jpg

**Comment by klinker24** [comment]
To be honest, I find that extremely confusing an misleading for the user, who - more than likely - isn't going to understand that they cannot simply add a participant without recreating the conversation.

I get why some people would like this, but I dont know if that is worth it for the app. I will have to think about this one, but the answer may be "no".

**Comment by klinker24** [comment]
I will go ahead and add this for `v2.5.0` of the app. 

**Implementation Notes:**

Within the group conversation, I just want to add an "Edit Participants" button. Clicking that will bring you to the compose screen, with the current participants active. From there, the user will be able to delete those, or add new users to the conversation.

This will just create a brand new conversation, with the contact list changed. It will be completely separate from the old conversation so that the user knows that no history has been carried over.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/6bddb4e98f214388dcfd15b424d3a1816ebd84b3
