### ISSUE TITLE
Global LED Notification Color

### ISSUE THREAD

**Issue by dchriste** [klinker-apps/messenger-issues#394]
Labels — `Feature Request` `Android` 

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <insert your device: OnePlus 5 on Android 7.1.1 (OOS 4.5.6)>
**Primary device:** <insert your phone: OnePlus 5 on Android 7.1.1 (OOS 4.5.6)>
**App version:** <insert version: App Version 2.4.7.1358>
**Steps to reproduce:**

1. Go to Global Settings -> Notifications / Alert Types -> "Test"
2. Observe that the system default color for Notification LED is used.
3. Observe that there is not currently an option in Alert Types for a global LED color.

**Additional information:**

In *suggesting this feature,* I am thinking of the way you programmed it into Evolve SMS. I previously worked around this with my custom ROM which gave me the ability to set a per app notify color for any app... I am no longer able to use that ROM on my new device, but I figured this would make a great feature addition to Pulse.

**Possible solution:**

I believe this feature makes the most sense to add a LED icon to the "Alert Types" menu, under Global Settings -> Notifications, which would call a color picker (just like the per conversation LED color you already have built in) to allow you to set the global pulse notification LED color. See attached image for a rough concept. 

![led-color_mockup](https://user-images.githubusercontent.com/1448498/28629668-18c45a0e-71f6-11e7-9d42-b6366d6a3e6f.png)

**Comment by klinker24** [comment]
At this point, this isn't something that I really want to add to the app. I talked about the hardware limitations behind it in this issue: https://github.com/klinker-apps/messenger-issues/issues/215

Especially now though, with Android O's notification channels, this isn't something that is going to be possible to support in future versions of Android. Everything is done on a per-channel basis, instead of globally. Android O really changes the way that notifications need to be thought about and is much more restrictive for apps that had previously done their own implementations of notification customization.

Android O removes the global ringtone, vibrate, and heads up options from this menu, as well.

**Comment by dchriste** [comment]
Thank you for your consideration. That makes a lot of sense. Even if you implemented it now, it would become deprecated as soon as O was released. Thanks again!

**Comment by gnc207** [comment]
Stock Android 7. The same thing here. Only 2 colors available, green and red and selected for SMS, but Pule still blinks Green on a new SMS. Would be nice to have Pulse to pick the right color from Settings.
