### ISSUE TITLE
Cannot send sms to some people

### ISSUE THREAD

**Issue by flef** [klinker-apps/messenger-issues#397]
Hi,

I have some contact with phone number in +33 x xx xx xx xx xx. In the pulse conversation, it's only written 33 x xx xx xx xx. Each time I try to send a new sms to this person the SMS is rejected. 

If I try to open a new conversation and type down the phone number +33 x xx xx xx xx, the conversation with my contact opens and the SMS is still rejected cause sent to 33 x xx xx xx xx.

Can you fix this bug please. 

:)

**Comment by klinker24** [comment]
You can probably delete the current conversation and then open up the new conversation by typing the number.

**Comment by flef** [comment]
Yep but I do not want to...

Envoyé par TypeApp<http://www.typeapp.com/r?b=10143>
Le 28 juil. 2017, à 20:26, Luke Klinker <notifications@github.com<mailto:notifications@github.com>> a écrit:

You can probably delete the current conversation and then open up the new conversation by typing the number.

**Comment by klinker24** [comment]
I am not sure what I am supposed to do for this one. Those numbers do match, so they should get bucketed into the same conversation, as is currently happening. That number would have been how it was imported into Pulse, so that is how it is stored in your internal messaging database, so that isn't a bug either...

**Comment by flef** [comment]
It is, I have plenty of messages in this conversation and from now I cannot send new ones.

Envoyé par TypeApp<http://www.typeapp.com/r?b=10143>
Le 28 juil. 2017, à 20:36, Luke Klinker <notifications@github.com<mailto:notifications@github.com>> a écrit:

I am not sure what I am supposed to do for this one. Those numbers do match, so they should get bucketed into the same conversation, as is currently happening. That number would have been how it was imported into Pulse, so that is how it is stored in your internal messaging database, so that isn't a bug either...

**Comment by klinker24** [comment]
Right, but it seems to me that the bug is not with me, but with your old app. If you send me an email, might be able to provide you with a version that will fix it, but there won't be any public changes for this issue. 

Please email luke@klinkerapps.com, I won't be able to fix it today as I am heading out of town. I can take a look at fixing it tomorrow. In the email, please provide me with what the phone number currently is, and what you would like it to be changed to.
