### ISSUE TITLE
Backwards/Forwards Navigation in Web App/Extension

### ISSUE THREAD

**Issue by seesemichaelj** [klinker-apps/messenger-issues#401]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.

**Device with issue:** Windows 10, Chrome v59.0.3071.115, Pulse Chrome Extension
**Primary device:** N/A
**App version:** Pulse Extension v1.9.0
**Steps to reproduce:**

1. Open up Conversations
2. Click on a conversation
3. Press Backspace or Alt+LeftArrow or press navigate back button on mouse (Logitech MX Master)
4. Notice the page has not navigated back to Conversations

**Additional information:**

This is a feature request to allow page navigation within the Pulse web app/extension, primarily for navigating backwards. This may/may not tie in slightly with #344, but I believe that issue has a larger scope than a simple backwards (and potentially forwards) navigation. This prevents me from clicking the hamburger menu and pressing Conversations (in my case, it is much more tedious to do this than it is to press the back button on my mouse)

**Comment by klinker24** [comment]
I would say that this directly ties to the mentioned issue.

Chrome extensions themselves do not really have a concept of "back navigation". If you were to use the Alt+LeftArrow on the web, you will see that it takes you back to the conversation list, as expected (unless you are focused on the text entry, of course).

Right now, there isn't really a bug here, and it is working as I intended it. 

I understand that not everyone likes the removal of the "back" button within a conversation's toolbar, but it is two clicks to open a different conversation, regardless of if you are backing out to the conversation list, or opening the drawer and selecting a conversation. 

In the future, with the keyboard shortcuts, I intend to make some different shortcuts available for faster navigation between conversations. But I would say that this issue is completely covered by the keyboard shortcuts issue.

**Comment by seesemichaelj** [comment]
I see now that web app does correctly implement back navigation.

Take this with a grain of salt as my boss is always complaining to me about number of clicks haha. Technically in the extension it is 4 clicks to get from one conversation to another (click hamburger menu, click Conversations, click outside of menu to make the menu disappear, click on another conversation). I wouldn't say it hinders me, but it does feel sluggish.

With what you said that Chrome extensions don't really have a concept of "back navigation" (and therefore you would need to know if you're in a conversation, the back button would mean to go to Conversations [instead of navigating back]), I can see how this issue can be considered as a duplicate of #344.

**Comment by seesemichaelj** [comment]
I guess I'll revise my statement that this issues is completely directed at the chrome extension and chrome app, not the web app (I apologize for not doing my homework and trying the functionality on each app).
