### ISSUE TITLE
"Sending..." Message Nomenclature Not Updated On Messages Successfully Sent and Received

### ISSUE THREAD

**Issue by TerrapinPi** [klinker-apps/messenger-issues#416]
**Device with issue:** SAMSUNG SM-G891A on Android 7.0
**Primary device:** SAMSUNG SM-G891A on Android 7.0
**App version:** 2.4.9.1391
**Steps to reproduce:**

1. I'm unable to reproduce at this time, however this behavior occurs on a daily basis.

**Additional information:**

Closing the app and restarting does not fix the issue. Rebooting the phone does not fix the issue. By clicking on a message the message's time stamp will display along with "Sending...". For example, "7:11 AM Sending...". I can confirm these messages reached the recipient.

Taking another look at it now it the "Sending..." message nomenclature only appears on messages sent today. That is, messages sent yesterday show only the time stamp. Come to think of it the messages displaying "Sending..." may have been sent from the Pulse web-app.

Edit: I just tried sending test messages using the web-app and the "Sending..." message is clearing as expected on the phone.

**Comment by klinker24** [comment]
It won't make a difference where the message is sent from, I don't have a whole lot of control over that process, to be honest. With Android, to send an SMS, you just call a system API. When sending from the web, it just forwards the messages to your phone to get sent there.

Android is also in charge of notifying the app when the message is successfully sent, through a broadcast receiver.

**Comment by klinker24** [comment]
I have made some changes and some refactors here that should take care of this issue: https://github.com/klinker41/messenger/commit/e49f95b4acdc5e1d63afe1b7ab660fb81755085a

They will come out in the next beta for `v2.5.0` or the production release, whenever that happens. Hopefully this is fixed.

**Comment by SeriousTube** [comment]
I have the same issue with Sending... not updating except in my case it is with your web app for chrome latest version, Version 70.0.3538.110 (Official Build) (64-bit). This seems to happen around half the time I send a message with your web app. I can reload the page and the Sending... notification will no longer display. I can also look at my phone and it will not display the message. I would classify this as an irritation rather than a showstopper but it would be nice if it were fixed.

My login for pulsesms is pulse@sallydown.com
