### ISSUE TITLE
MMS picture + long message prevents you from seeing what is being typed

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#42]
**Device with issue:** Moto Z Force
**App version:** 1.1.209
**Reported At:** https://plus.google.com/u/0/+JosueJoseph1991/posts/9PvWY25cnyn
**Steps to reproduce:**

1. Add an picture
2. Type a long message
3. The message will go off of the bottom of the screen, underneath the keyboard

![16 - 1](https://cloud.githubusercontent.com/assets/4874287/18129572/e8b0a6a4-6f50-11e6-906c-5e6f75efb749.png)

**Comment by klinker41** [comment]
Idea for this one: currently we set a constant height to the image that is attached to the message and that along with the toolbar is taking up all of the screen space. Maybe if we were to instead just set a max height on the image, then it would be allowed to shrink as the message entry area expanded.

**Comment by klinker41** [comment]
fixed with https://github.com/klinker41/messenger/commit/a12fb26bade862a800963dad31e19e371db34ee2

I changed it so that the attachment view takes up 1/4 of the space that the message list does when it is showing so that it will resize dynamically as the space gets smaller. When the keyboard is showing in landscape mode however, this gets to be extremely small. Still better than not seeing the text at all though I would say.
