### ISSUE TITLE
Use Separate notifications for each message on Android

### ISSUE THREAD

**Issue by jasonlyle88** [klinker-apps/messenger-issues#427]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Nexus 6P on Android 7.1.2
**Primary device:** Nexus 6P on Android 7.1.2
**App version:** 2.5.1.1452
**Steps to reproduce:**

1. Recieve multiple messages from the same contact without reading previous messages

**Additional information:**

Android automatically collapses multiple notifications from the same application down into one notification that the end user can then expand. Instead of your app concatenating multiple messages from the same contact and separating those messages with a "|" character, just use separate notifications.

**Comment by klinker24** [comment]
Sorry, this one is not planned to change. When content comes in that generates the same type of notification, then it should be appended to the current notification, rather than generate a new one. 

This is discussed in the first paragraph on Android's "Managing Notifications" page: https://developer.android.com/training/notify-user/managing.html

> When you need to issue a notification multiple times for the same type of event, you should avoid making a completely new notification. Instead, you should consider updating a previous notification, either by changing some of its values or by adding to it, or both.

This is something that I definitely agree with. Notifications can get out of control extremely quickly, I don't want my app to contribute to that. Since new messages coming in to a conversation are the same content, I do want to continue to append them to the current notification, rather than to generate a brand new notification
