### ISSUE TITLE
vCard Previews

### ISSUE THREAD

**Issue by DavidCao22** [klinker-apps/messenger-issues#434]
**Device with issue:** Google Pixel
**Primary device:** Google Pixel
**App version:** 2.5.2.1459
**Steps to reproduce:**

1. Open a conversation
2. Share a contact

**Additional information:**
As a user sharing contacts, I would like to see previews of contacts/VCards I have already shared so that I know whose info I have sent. This would help with double checking that I sent over the correct contact. Google Messenger displays previews of the contact cards, and tapping the preview expands it to show the full contact without importing it. Tapping the contact in Pulse immediately starts the contact import process, which I don't want to do if I'm just checking to see if I sent over the correct contact.

#332 is about a somewhat related VCard location sharing issue. This is more a feature request for VCard previews as a whole. 

Pulse displaying contact previews:
![screenshot_20170827-101544](https://user-images.githubusercontent.com/10539139/29751516-16efe86a-8b14-11e7-92f8-9bf245917a4e.png)

Google Messages displaying contact previews:
![screenshot_20170827-101600](https://user-images.githubusercontent.com/10539139/29751532-4943f036-8b14-11e7-98a9-74298f76ec52.png)

Google Messages displaying a single contact in full detail:
![screenshot_20170827-103206](https://user-images.githubusercontent.com/10539139/29751534-4eb51f04-8b14-11e7-94f7-6c46a9e9f013.png)

**Comment by klinker24** [comment]
Yes, this will definitely need to be improved in the future

**Comment by klinker24** [comment]
This has it's initial implementation. It isn't going to see a full rollout for quite some time though. I hope to release it for `2.11.0`, to allow for testing different cases and different types of vCards, through a feature flag.

It should display multiple contacts just fine, within the vCard. It will show any phone numbers that are included, too. It just creates a new entry below the vcard, with the contact information:
![device-2018-02-15-170653](https://user-images.githubusercontent.com/4874287/36285839-cfbfa11a-1272-11e8-8864-e77f17562646.png)

The other side of this issue was parsing locations from iPhones. In the previous comment, I have some example vCards that support location. They will display a static Google map, below the vCard. Clicking the map will open Google Maps:
![device-2018-02-15-170250](https://user-images.githubusercontent.com/4874287/36285880-ef60aa1e-1272-11e8-8b92-f8a92f3f7e24.png)

I'm sure that there are cases and vCard formats that I haven't covered, but I am happy with this implementation for now. It will continue to roll out over the next few months. I will also need to add support for the `media/map` mimetype, on the web and iOS apps, so that they can parse the lat/long coordinates and display the map, too.

**Comment by DavidCao22** [comment]
@klinker24 Sweet! Thank you!

**Comment by pyurga** [comment]
Any ETA on when this 2.11.0 version is going to be released?  Still seeing 2.9.3.1982 on the play store.  Looking forward to seeing this feature.  Thanks for taking the time to implement it.

**Comment by klinker24** [comment]
2.10 will be released sometime this month. This is currently rolled out to 25% of users for testing. I will never be able to provide an ETA, sorry

**Comment by pyurga** [comment]
No worries at all and I appreciate the reply.  I will be watching out for
the upcoming releases and will consider switching back once this particular
feature rolls out.


--
