### ISSUE TITLE
Swipe between unread conversations

### ISSUE THREAD

**Issue by uudruid74** [klinker-apps/messenger-issues#446]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

This is a feature request.  Would it be possible to implement some sort of swipe functionality to move between different active conversations or perhaps conversations that have new messages in them?   This would make it very fast to quickly go through all new messages and answer them all.

I don't know if you'd add a tab indicator and some little animation to swipe between tabs or just whole screens ... that part doesn't interest me.  But going back to the top of the phone and clicking the arrow (one handed can be a pain) to select a new conversation feels kinda "clunky'.  Swipe to next unanswered message would be amazing!

**Comment by klinker24** [comment]
Sorry, this is not something that will come to Pulse. Our other app, EvolveSMS was built around this, and that is part of the reason that we didn't do Pulse this way. Every load time is slower, it isn't as clean, it is harder to manage. 

I understand the usability side, which is why EvolveSMS (and Sliding Messaging before that) was built around this. This is not something that Pulse will be doing, though. Too many drawbacks
