### ISSUE TITLE
Blacklist with bulk-sms senders

### ISSUE THREAD

**Issue by amard33p** [klinker-apps/messenger-issues#447]
**Device with issue:** Nexus 4
**Primary device:** Nexus 4 on Android version 6.0.1
**App version:** 2.5.3.1475

Issue observed with [bulk-sms sender](https://www.quora.com/What-is-the-meaning-of-DM-TA-LM-DZ-MD-etc-in-the-name-of-bulk-sms-sender) contacts. I don't know whether these are specific to India. These "Sender-IDs" are used by companies to pester users with promotional texts. However banks also create their own "Sender-IDs" to send OTPs for transactions, among other things.

**Steps to reproduce:**

1. Blacklist sender VM-LIFSTL or VK-LIFSTL. This is used by the Lifestyle e-commerce company to send promotional texts.
2. Now messages from VM-HDFCBK or VK-HDFCBK which are used by the HDFC Bank to send OTPs are blocked.

**Additional information:**
This was a particularly frustrating bug. I was using Textra before and decided to try Pulse mainly because of the notification actions. I manually migrated my Textra blacklist over to Pulse. Now today, in the middle of a bank transaction I notice the OTPs are not coming. Long story short, I restored Textra from Titanium Backup (so that it restores the blacklist), changed default sms app to Textra and bam...OTPs arrive without a hitch. After a few painstaking hours, I managed to narrow down the blacklist to 2.
I am not sure how these "Sender-IDs" work. I also don't know how Pulse's blacklist works. 
All I know is, given the same blacklist, Textra works fine.

**Related Issue:**
Even if a contact is added to the blacklist, you can add it again and it will create a duplicate entry. This goes for both normal contacts and bulk senders.

**Comment by klinker24** [comment]
So Pulse uses Android's internal [PhoneNumberUtils#compare](https://developer.android.com/reference/android/telephony/PhoneNumberUtils.html#compare(android.content.Context, java.lang.String, java.lang.String)) method to check what is received against the plain text that you have input into the blacklist. Hmm. It would be using this comparison: 

https://github.com/android/platform_frameworks_base/blob/master/telephony/java/android/telephony/PhoneNumberUtils.java#L457

**Comment by klinker24** [comment]
This has been fixed with: https://github.com/klinker41/messenger/commit/64d8aa3c6866a0bcc0f72ade30f309fa4270194f
This verifies the correct behavior and that the old Android utility was providing inaccurate results: https://github.com/klinker41/messenger/commit/b9abe4e09048d5612c7ae94fb49334105b1d4b17

Thank you for the detailed bug report on this issue. Sorry it has taken me some time to fix. I wanted to make sure I got it right and that I was able to verify the results of the old method (from the Android SDK) as well as the new method that I built internally to Pulse.

This will be rolled out with the next release of the app (`v2.6.2`).
