### ISSUE TITLE
Notification issues with active conversation

### ISSUE THREAD

**Issue by uudruid74** [klinker-apps/messenger-issues#455]
**Device with issue:** Android
**Primary device:** 1+3T
**App version:** Latest Beta

Sometimes, when I have the app open, I'll get heads up notifications for the conversation I have open.  It's not just redundant, but having the heads up and the keyboard both open leaves little room for the actual conversation.   This is happening on multiple devices with radically different ROMs (one CM13 based, an EAS/CAF/AOSP Nougat ROM, and DU Nougat).

**Possible solution:**
Don't show notifications when the relevant conversation is open.

**Comment by klinker24** [comment]
You say "sometimes". How often is that?

Pulse is designed to not give notifications when the conversation is open.

**Comment by uudruid74** [comment]
Once it starts doing it, it's consistent, and its starts pretty frequently, but not always.   I've not yet discovered a specific pattern as to when it does it or if its something in my setup.  I'll keep experimenting and keep this updated if I discover anything.

On Sep 14, 2017, Luke Klinker <notifications@github.com> wrote:
>You say "sometimes". How often is that?
>
>Pulse is designed to not give notifications when the conversation is
>open.

-- Sent with K-@ Mail - the evolution of emailing.

**Comment by klinker24** [comment]
I think this issue will be fixed with these changes. https://github.com/klinker41/messenger/commit/ce3d2fa1bf0ca4cdec400833b498fedb8b02fa02

**Comment by Skullmonkey** [comment]
Sorry to ask: Any ETA for 2.6? I had to switch back to the stock app because of my version of this issue.

**Comment by klinker24** [comment]
This will get released with the next beta. 

I hadn't heard from anyone else on this issue though, so it seems unlikely to be so persistent that it would force you to change apps. Are you sure this is the issue you were seeing?

**Comment by Skullmonkey** [comment]
My issue is referenced in this one, Basically I sometimes get no notifications when I receive a text. When I unlock my phone, instead of going to the conversation I had active when I locked my screen, it goes to the conversation list with the previously active one showing as new message received. I have not noticed if I do not receive any notifications but definitely doing it for the one I had active. I need my text notifications to be always working for my line of work which is why I went back to the stock app until this gets fixed. I love it otherwise for the ability to text from my computer.
