### ISSUE TITLE
Swap swipe actions for delete and archive

### ISSUE THREAD

**Issue by talha131** [klinker-apps/messenger-issues#472]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** LG G4
**Primary device:** LG G4
**App version:** 2.5.7.1591

Currently swiping from left to right is for archive action and swiping from right to left is for delete action. 

On the other hand, Google Inbox has these actions reversed. In Google Inbox app, left to right is for delete action and swiping from right to left is for archive action.

Will you please add an option to swap the swipe actions or just swap the actions by default? 

I searched Google design documentation and couldn't find any recommended swipe direction for delete or archive. But it would be a great help if Pulse is consistent with Google Inbox. In the past I have deleted messages by mistake when I actually intended them to archive.

**Comment by klinker24** [comment]
Sorry, this is working the way I intended it. 

I chose those directions so that opening the drawer doesn't accidentally cause the user to delete a thread. That is the only other horizontal swipe gesture in the app, so they could conflict.

Also, inbox, by default has swiping from the left to right mark as done, which is similar to archive. I think that the way I have it now is how it needs to be

**Comment by nblyumberg** [comment]
I just sent this as a feature request but I see you provided feedback there. I think this should be up to the end user to decide which way this works. Prevention of accidentally deleting is something by forcing a specific way isn't really a solution because for every person who does it one direction, there is another person who does it in the opposite direction. Those opposite people would be deleting things accidentally as well. That's why having an option for this makes for a better UI. Your justification is also handled by the hamburger to expand the settings pane rather than swiping.

**Comment by klinker24** [comment]
If you are worried about accidental deletion, I recommend turning off swipe to delete all together. You can still long press the conversations to quickly delete them.

Adding a setting for a UI tweak is what I want to avoid in Pulse, like I said. While I understand that some users want to customize everything and need everything their own way, that really isn't my goal here because it distracts from the app itself and it's features. 

There are some things that I do need to just make the decision on, to add that simplicity factor. Many more users care about simplicity than complete customization and tweaks. I feel as though Pulse's success so far is a testament to that fact.

At this point, I am not going to be open to adding a setting just to customize swipe direction, sorry about that. Hopefully my reasoning makes sense
