### ISSUE TITLE
Receiving MMS as group chat

### ISSUE THREAD

**Issue by Shift12H** [klinker-apps/messenger-issues#479]
I am having an issue where when MMS is received from others, the pictures are displayed in a separate group chat between myself and the sender. In the past, the MMS appeared in the senders existing text msg chat. 

I have a Samsung  galaxy s7 running Android 7. My app version is 2.5.7.1591.

**Comment by klinker24** [comment]
We track all mms issues in #101. I can answer your question here though.

Some phones do not provide the correct phone number for your current device. When the app has your correct phone number, it will strip it out of any incoming messages, so this wouldn't happen. Since it isn't always reliable to query the device's phone number, I allow you to insert the phone number in the top preference of settings.

So, if you open *Global Settings* and touch the top option, you can enter you own devices phone number and it will strip it out of incoming messages. This will take care of your issue.
