### ISSUE TITLE
Clicking on desktop notification opens new window everytime

### ISSUE THREAD

**Issue by kirstilynn** [klinker-apps/messenger-issues#495]
**Device with issue:** MacBook Pro on MacOS 10.12
**Primary device:** <insert your phone: "Pixel XL on Android 7.1.2">
**App version:** Mac Desktop v1.0.0-beta6
**Steps to reproduce:**

1. Close any Pulse windows
2. Click on "new message" desktop notification when you receive a message
3. A new window will appear.
4. Click on "new message" desktop notification for the next message you receive
5. It will open another new window
6. Click on the Pulse icon in your menu bar
7. Another new window will appear.

**Additional information:**
This seems to only occur if I don't have the window open that is opened by click on the menu bar icon. If I have that open, then clicking "new message" will use that open window. But if I don't have it open, it will keep creating new windows every time I click on the notification for a new message.

**Comment by klinker24** [comment]
By "menu bar", I assume you are talking about the dock?

**Comment by kirstilynn** [comment]
Yes, the icon in the dock.

**Comment by klinker24** [comment]
I am not able to replicate this issue and I am not sure I follow your *additional information* section. Could you walk me through how you are opening the app, getting the notifications, then getting the duplicates?

There were duplicate windows a while back, similar to this, but those were fixed and I haven't seen or heard of this issue since. If you could clarify some of the steps, that would be helpful. It would be best to start from scratch, where the desktop app is completely closed (by right clicking on it and selecting "quit"). When the app is in this quit state, it will not provide notifications at all, so you will need to open the app and go from there.

**Comment by kirstilynn** [comment]
I will try to post a video of it when I get a chance.

**Comment by klinker24** [comment]
I would probably rather have the step by step description/walkthrough. 

I definitely know the outcome here and what you are experiencing, I am much more concerned about how you are getting to that point, rather than what is happening as the result.

**Comment by kirstilynn** [comment]
1. Open Pulse (Assuming you are opening from a quit state)
2. Close the window (Don't quit Pulse, just close the window)
3. Click the "new message" desktop notification
4. A window will open
5. Now click on the Pulse icon in your dock
6. A new window will open

My additional comments section was trying to say that if I start Pulse, and keep that main window up, this issue will not happen, and clicking desktop notifications just use that same open window. If you can't recreate this I can create a video of these steps to show you how I can recreate it.

**Comment by klinker24** [comment]
Thank you, that is what I needed.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-chrome/commit/843c6af2ee3ab9f55b1bdb720d5d90ea8808637a

It will be released with the next  beta version of the desktop app (`beta-7`).
