### ISSUE TITLE
Feature request: Unread from here

### ISSUE THREAD

**Issue by hudcap** [klinker-apps/messenger-issues#526]
Great collection of apps! Thanks!

When multiple new messages come in to a single conversation, there is no way to know which messages are new and unread. I'd like to request a divider in each conversation marking where the unread messages start.

**Comment by klinker24** [comment]
Glad you like them, thanks! Admittedly, this isn't something I am super keen on adding...

- From a functional standpoint: 

Pulse has always revolved around unread conversations, rather than unread messages. This is pretty common for an SMS app I would say. If we are adding a prominent element to the UI, then it needs to work exactly how the user expects, every single time. So what if the user dismisses a notification? Does that mark the message as read or should it keep the message unread? What if that notification is dismissed from a different device? What if the app is open to a conversation on one device, and you go to look at the message on another device. I don't think it is safe to assume that people would have the same answer to these questions.

- From the UI/UX standpoint

This is not something that I would want to add a settings toggle for. From the start, with Pulse, I have said that I don't want to fill the settings with little tweak options. Pulse is about the feature set, not digging through settings, and I really want to stick to that philosophy. I want to fill Pulse with features that everyone enjoys, not features that are distracting or will get in the way for users. While this request might be helpful to some, for many, that is just one more thing on the screen to get in the way

I am not sure that I like the idea of having a divider breaking apart the message list either. Messages are each their own entity/view, unlike the conversation list that groups *full screen* views into time series. In my opinion, breaking apart the message list just wouldn't look good.

---

Right now, I am leaning towards a "no" on this one, sorry about that... Let me think about it over the next few days though and consider other possibilities. Feel free to comment back and try to sway my opinion on this as well

**Comment by hudcap** [comment]
Wow! Thanks for the detailed response!
I will attempt to address each of your points.

- Motivation:
Suppose there is a long conversation. now 10 new messages come in. You want to read all the new messages. How far back should you scroll? This can be a real annoyance, especially for texts from e.g. Twitter and other text notifications, which have no "replies."

- Notification dismissal:
I would argue that the same rules that apply to marking a conversation as read should apply to marking a message as read. In fact, each message should **not** have it's own read/unread status, but rather a conversation that has an unread status should also have a marker that marks where that status starts within the messages. I did not intend for this to be like emails, where each message has it's own status.

- Divider:
I notice that messages are already grouped by time &mdash; messages sent within some window of each other are grouped together and divided from other messages with a timestamp, so you must not be *completely* opposed to dividers in the message list :-D
That said, I am not dead-set on a divider - any visual indicator is fine with me, e.g. different color message background. Even jumping to the location of the first unread message would likely solve this.

Please let me know how I'm doing in the polls :)
Thanks again!

**Comment by klinker24** [comment]
The second point, with when messages should be unread is my real sticking point here. It doesn't matter how we track the messages that are unread/read, just that they are tracked. The two methods you mentioned for tracking this are the exact same from the user-standpoint, so that isn't really what I need to discuss. That is just an implementation detail, definitely not what I am worried about

Currently, when you dismiss a notification, that conversation is not marked as read, but chances are, you dismissed that notification because you did in fact read that message. Hence my sticking point there. When we are getting into the granularity of messages, I don't agree that they should act the same as conversations as a whole, since they are different entities for different purposes. Conversations are meant to be accumulators of the messages under them

For the last UI point, I consider the timestamps a part of the messages, not dividing them. They are directly attached and correlated with the message above them, so I don't really agree there... The divider that we are discussing is fundamentally different than the messages. As it should be, a divider should definitely be distinct from the content it is breaking apart. 

I don't think changing the background color of the message is the way to go either, that would be higher on my "yikes" meter than just adding a divider. I also am not keen on the idea of jumping to that point in the list. I am of the opinion that the latest message in the conversation is the most important. So even when messages are unread further back, that newest message is where the conversation should start


I definitely get the motivation behind this topic, I am just not sure it is the right fit for Pulse and I am not sure it could work with user expectations

**Comment by klinker24** [comment]
I think that at this time, I am not going to implement this, sorry. I am going to put a `watch` tag on it though and will consider re-visiting it in the future
