### ISSUE TITLE
Conversations settings page

### ISSUE THREAD

**Issue by bcurran3** [klinker-apps/messenger-issues#534]
I use my phone very little. I use the Pulse SMS website a LOT for texting. There are some temporarily important conversations that I'd like to pin via the website. The ability to pin conversations via the website would be beneficial (to me!).

**Comment by klinker24** [comment]
I will probably make this more extensive than just the pin/unpin status. I should implement the settings that are relevant to the web and have them editable, here.

* [ ] if it is a group, they should be able to edit the group name
* Toggles (with the summary description if applicable):
  * [ ] Pin conversation
  * [ ] Mute conversation
  * [ ] Private conversation
* People always asked to be able to use hex colors for the conversations... This could be the place to do it. Tell them if they want that functionality, it is available on the web
  * [ ] Primary color, primary dark color, accent color
  * [ ] link to a color generator or something, so that the users will know what these are and what they mean

This page should have a "save" button at the bottom, which will make the web request, then return to the conversation list to pick up the changes.

**Comment by klinker24** [comment]
![screen shot 2018-01-28 at 7 43 06 pm](https://user-images.githubusercontent.com/4874287/35490189-7d86be8c-0463-11e8-98b3-09d822429efb.png)

This is now finished with the above settings available on the web. It will be rolled out throughout the following week.

* create navigation: https://github.com/klinker41/messenger-web/commit/8f2d344b1fdb723352f838ea818435d8d7c9cc53
* display settings: https://github.com/klinker41/messenger-web/commit/24010bd317a2f8e6781e6bed0db508a48bfc15d4
* allow for dialog input: https://github.com/klinker41/messenger-web/commit/e159b7c0e145aee96fa463d657e206f8d472d91a
* post changes to backend: https://github.com/klinker41/messenger-web/commit/1f5b47300d8fa91bbe0919a8da305c0ad22f9ef3
