### ISSUE TITLE
MacOS getting duplicate notifications

### ISSUE THREAD

**Issue by jwkicklighter** [klinker-apps/messenger-issues#545]
**Device with issue:** MacBook Pro 10.11.6
**Primary device:** Pixel XL 8.1.0
**App version:** 2.7.2.1822 (desktop version beta12)
**Steps to reproduce:**

1. Receive a message while MacOS app is running

**Additional information:**

There is one notification that looks native with the inline Reply button and one that is just the icon without any preview text or buttons.

**Comment by klinker24** [comment]
We are up to RC2 on the desktop apps, you should try that version.

**Comment by jwkicklighter** [comment]
Oh weird, looks like it stopped auto updating. I'll install that.

**Comment by jwkicklighter** [comment]
@klinker24 Still receiving double notifications on RC2.

**Comment by klinker24** [comment]
If you can give me more information for when, that would be nice. I am not seeing this, nor have I heard about it.

**Comment by myspivey** [comment]
I am seeing the same. Any notification of a new txt. On RC2. 

![screen shot 2017-12-22 at 11 05 54 am](https://user-images.githubusercontent.com/2472925/34308019-549bb874-e708-11e7-90d0-daa3aba73d73.png)

**Comment by jwkicklighter** [comment]
Yeah, it seems to be reliably happening with every text like @myspivey says

**Comment by klinker24** [comment]
That screenshot was really helpful, thank you. The issue wasn't with the native app, it was with the web interface that the native app renders.

When the web app was in the background (like it always is when the native app is minimized or closed), there were cases where the web could provide notifications on top of the notifications from the native app. The web's notifications, coming through the native mac app were just blank, since the mac app didn't support some of the same properties.

I will push out the fix.
