### ISSUE TITLE
Sync messages after network outage

### ISSUE THREAD

**Issue by BertoMejia** [klinker-apps/messenger-issues#553]
First of all Kudos. I just downloaded the app yesterday, and I really like what you've done. Your app is very clean and useful, with all the right features. I am thinking of buying the lifetime membership, but I'm already having issues.

When I was on a call and with no Internet (stupid Sprint and their no Internet during calls!), messages I received did not sync with the server.

**Device with issue:** Samsung Galaxy S7 Edge - Sprint
**Primary device:** Same as above
**App version:** 2.7.3.1839
**Steps to reproduce:**

1. Remove Internet
2. Receive Text message
3. Check Web (Unfortunately, this didn't happen every time, but it did happen more than once for me.)

**Additional information:**

I know I can destroy the account and recreate it, but I would prefer to fix the root of the problem or add a less destructive sync function. Furthermore, if I try to send messages from the web while there is no Internet, and they don't sync, destroying the account and recreating it would lose the messages I wrote on the web. (This hasn't happened but is my biggest reason for leaving Mighty Text, so I thought it's worth mentioning)

MySMS has a "Force Sync" feature that that seems to work very well in these type of scenarios.

**Possible solution:**

I'm not going to pretend to know enough about your code to give you a solution, but here are some suggestions possible solutions. I hope it helps.

1. Please add a "Force Sync" option to push and pull messages to and from app. This will reduce issues with text messages not syncing properly.
2. Create a received receipt in server, have phone app keep trying to send periodically until received receipt arrives.

**Comment by klinker24** [comment]
Use the "refresh account" option in the phone's account section as a force sync option, that is already implemented.

**Comment by BertoMejia** [comment]
Ok, sure. However, I'd like to fix source the problem. Is this something you think is possible?

**Comment by klinker24** [comment]
I mean, that was one of your two fixes, but this is something I would like to fix the root cause of, if that is what you are asking me.

**Comment by BertoMejia** [comment]
Thanks for the quick responses.

Yes, that is what I was asking. The solution you responded with was something I originally said was not what I was looking for.

I would definitely like to not have these issues at all. However, if it happens occasionally then simple one-touch solution that doesn't make you re-register everything and re-login to everything would be much better.

Keep in mind I've had this app for 1 day, and I'm already having problems. So, my first thought is, "am I going to have to re-register and login into all my devices every day?"

With that being said, I say that as constructive criticism because so far, outside of those problems, I really like your app. I'm just trying to help both you make a better app, so I can buy your service and enjoy it.

**Comment by witcradg** [comment]
Is this the same issue? Messages written on my phone do not always appear on the PC application.

**Comment by klinker24** [comment]
Anyone will see this issue if you don't have an active network connection when a message is sent or received. 

That app doesn't work the same way as Pulse. Of course, the idea here is to push up all the missing messages. That is what this topic is about. A periodic upload will not do, since the goal of Pulse is to have your messages available as they come in. When the phone regains an internet connection, the messages would need to get uploaded, not an hour after-the-fact. That is just a workaround. When I do this, it will solve the root cause of this issue, I don't want to just put a bandaid over the issue.

**Comment by chiypg** [comment]
Thank you for your reply.

You are right that it is important to have the messages uploaded when they come in in Pulse. However, it is also important to have complete messages on server in Pulse, even they are not uploaded in time for connection outage. For example, I want to look for some information in previously received messages. It is frustrated to find the messages are incomplete on web and my secondary device.

You are also right that the best way to solve the issue is to upload the messages when the phone regains a connection. However, it is also important that how difficult the fix is. Or, in a customer's perspective, when the fix will be available. It's good, if the fix will be available in a month or two. However, if it will take years to have it fixed, then it is important to make sure the messages are complete, sooner, even they are not uploaded in time. Both periodically uploading and uploading missing messages when a new message comes in would do the job. And I supposed they are easier to implement.

I don't think it is practical to use "refresh account" as a workaround. It is too slow to do it everyday. And it doesn't handle blacklist, deleted messages, and archived messages. So it would be nice to have a fix soon.

**Comment by klinker24** [comment]
It won't take any longer to actually fix this issue than it would to provide your suggested workarounds for this issue, no.

**Comment by klinker24** [comment]
I have made changes around this that I will start to test more thoroughly and roll out to all users, over the next few months.
