### ISSUE TITLE
Notifications by conversation produce no sound

### ISSUE THREAD

**Issue by wrhight** [klinker-apps/messenger-issues#560]
**Device with issue:** Primary device.
**Primary device:** Pixel XL
**App version:** 2.7.5.1855
**Steps to reproduce:**

1. Turn up ringer volume, maybe link account
2. Receive SMS Text
3. ---> No sound

**Additional information:**

On Android Oreo, I have all conversations on "urgent" and vibrate. No notification from Pulse produces vibration or sound, but it does activate the notification light. Other SMS apps, or any other appa do not have this issue. I have paid with a lifetime subscription.

I also looked on the google+ group, [this conversation](https://plus.google.com/+AlexKruger/posts/5T2xDmzixuk) proves multiple users are experiencing the same thing. One user mentions after linking his account, notifications no longer produced sound or vibration. This also only occurred after linking my account.

It seems I receive sound from MMS

**Comment by klinker24** [comment]
I'm not really sure what to say about this. You can long click any notification to open up it's channel settings and see how it is configured. I literally have no control in Oreo, everything is hijacked by Android. If I do not provide a channel, then the notification isn't displayed at all.

Unfortunately there is no precedent for debugging, since Oreo is brand new. Could it be that I have created too many channels and Android doesn't understand how to handle them? There is nothing in the documentation about that. I am open to suggestions though.

Here is the documentation on notification channels: https://developer.android.com/guide/topics/ui/notifiers/notifications.html#ManageChannels

**Comment by trentchristopher** [comment]
I am also having this issue. Sent email with details yesterday. 
Pixel 2
Oreo 8.1.0 January 5th security patch

I went through as many notification channel settings that I could find, and made sure they are all set to urgent, still no sound, or vibration.
-Trent

**Comment by wrhight** [comment]
I have a little more information.

Conversation notifications will vibrate with two short bursts, similar to other apps, if Android is set to vibrate only on the ringer. With MMS, the vibration is two longer bursts similar to how Android Messages vibrates for me. WIth the ringer on, neither vibrate or sound plays. Tested this with a friend, he experiences sound and vibrate as normal.

**Comment by klinker24** [comment]
I have a feeling that Google changed something (or messed something up), with the Jan 5th security patches.

I have reduced the number of channels and simplified their setup, for the next version of the app. Will probably release it to beta tomorrow.

**Comment by wrhight** [comment]
I have noticed that during the message backup, whenever you create a new notification to update the progress bar, it spams the user with sound and vibrate every time the progress is updated. I understand this is an Android thing right now, but there should be some way to dial that down.

**Comment by klinker24** [comment]
I don't think that has anything to do with this issue, but you could change the priority for that notification, through notification channels.

**Comment by trentchristopher** [comment]
Ok, so it has to do with the notification channel "status notifications"....if that channel's "importance" is set to "medium:no sound" then my sound and vibration returned.

I discovered this by toggling all channels off then back on, except "default conversation"...this "fixed" the issue. I think because it resets the importance. I then worked my way down the list changing the importance back to "high:make sound" one at at time. Issue returned when I got to "status notifications".

**Comment by wrhight** [comment]
I can confirm fiddling with the "status notifications" channel fixed the issue with my phone and my friend's. I turned this to medium and vibrate and sound were working. For my friend, he had to turn it to high and turn vibrate on for his vibrate to work in addition to sound. We both have Pixels, on the latest Android security update.

**Comment by klinker24** [comment]
Ok. 

I removed that channel and condensed notifications for the next version of the app. I don't understand why those steps would affect anything, it is pretty clear that the notifications are not going through that status channel (you can verify that by long clicking the notification to view the channel). I have no clue why the status notification channel would do anything.

If one of you could sign up for the beta then follow-up with the next release of the app, that would be helpful. I will release it tomorrow morning to the beta channel.

**Comment by klinker24** [comment]
I got confirmation that this is working fine in today's beta update, so going to close this.
