### ISSUE TITLE
Validation if message was send

### ISSUE THREAD

**Issue by Jatarii** [klinker-apps/messenger-issues#593]
It would be nice if there was a notification or other on the web to make it clear that a message was actually send ON MY PHONE. Now I send a message through the web and it is sometimes not sent on my phone.

**Comment by klinker24** [comment]
This adds a toggle to the settings section of the web/desktop apps to display a sending status: https://github.com/klinker41/messenger-web/commit/44f1a3b3e8c39a152fa4e41bcbb03f4f273f79f0

The default is having this turned off and I don't know if that will ever change. You may occasionally see issues with that status not updating correctly when a message does go through to the phone. This is because the web has never tracked this status before, so it is a low priority update. It should work fine for the vast majority of cases, though.

I will deploy it later today.
