### ISSUE TITLE
Request for API 

### ISSUE THREAD

**Issue by brokrbindr** [klinker-apps/messenger-issues#647]
Good day. We publish a web app for a certain vertical market in the Canadian FinTech market. Our clients are able to use our app to send SMS messages to their customers. We currently use Twillio but are looking for an alternative that will send messages from our clients' real number and allow responses back. The API should allow all correspondence (inbound and outbound) to be captured in a communications log in our product (https://BrokrBindr.com/). I found no reference to an API on your website or in Github. Do you have any plans to offer such an API? Joseph Valenti joe@brokrbindr.com

**Comment by klinker24** [comment]
Pulse's API is by no means hidden. If you inspect the JavaScript on the web, it is very easy to follow the requests. There is no public documentation though, and you would need to deal with the sign on and end-to-end encryption, which are both non-trivial.

I have open-sourced an iOS client that can access and use Pulse's API. It should provide a good base for anything you are looking to build: https://github.com/klinker24/messenger-ios



Unless you are building a new Pulse client, when people ask me about using Pulse's API, I always say that they are welcome to it, but I highly doubt that it fits your needs. 

The API really just facilitates device-to-device communication, it doesn't do any of the sending or receiving itself and it doesn't really have any applications for people that aren't Pulse users. All it does is forward changes you make on one device, to the other devices on the account, and persist those changes to the backend database. It isn't the same thing as Twilio and is definitely not a replacement for that.

I haven't made any public documentation because it really has a shallow focus and is only designed to be used inside of Pulse. I can't really see any applications outside of my own app.

**Comment by brokrbindr** [comment]
Good day, Luke

Thank you for your thoughtful reply. I will consider your comments.
You have a great piece of software, there, and I look forward to more interesting output from Klinker Apps.
Have a great weekend.

Joseph Valenti
Co-Founder and Customer Advocate

Discover why BrokrBindr is a better way to manage your mortgage brokerage business by registering for our webinar at 1pm, daily (https://link.getmailspring.com/link/1523623624.local-c10bb263-92a8-v1.2.1-7e7447b6@getmailspring.com/0?redirect=https%3A%2F%2Fbrokrbindr.com%2Fschedule-a-call%2F&recipient=cmVwbHkrMDIyMmVhMzdkMjNmZjU4M2NmMDhlZWM5MzZjZmI3MzIzNjJiODViNDlmMmMwNWIzOTJjZjAwMDAwMDAxMTZlODUzNDQ5MmExNjljZTEyYjcwYjU5QHJlcGx5LmdpdGh1Yi5jb20%3D)
Email: joe@brokrbindr.com (https://link.getmailspring.com/link/1523623624.local-c10bb263-92a8-v1.2.1-7e7447b6@getmailspring.com/1?redirect=mailto%3Ajoe%40brokrbindr.com&recipient=cmVwbHkrMDIyMmVhMzdkMjNmZjU4M2NmMDhlZWM5MzZjZmI3MzIzNjJiODViNDlmMmMwNWIzOTJjZjAwMDAwMDAxMTZlODUzNDQ5MmExNjljZTEyYjcwYjU5QHJlcGx5LmdpdGh1Yi5jb20%3D)
Direct (Woodbridge): 289-536-2220 (tel:289-536-2220)
Montreal (Beaconsfield): 514-444-1556 (tel:514-444-1556)
Ottawa (Stittsville): 613-913-6787 x302 (tel:613-903-6787)
Calgary (Vista Heights): 587-774-4888 x302 (tel:587-774-4888)
Address: 40 Winges Rd, Unit 4, Woodbridge, ON, L4L 6B2 (https://link.getmailspring.com/link/1523623624.local-c10bb263-92a8-v1.2.1-7e7447b6@getmailspring.com/2?redirect=https%3A%2F%2Fmaps.google.com%2F%3Fq%3D40%2520Winges%2520Rd%252C%2520Unit%25204%252C%2520Woodbridge%252C%2520ON%252C%2520L4L%25206B2&recipient=cmVwbHkrMDIyMmVhMzdkMjNmZjU4M2NmMDhlZWM5MzZjZmI3MzIzNjJiODViNDlmMmMwNWIzOTJjZjAwMDAwMDAxMTZlODUzNDQ5MmExNjljZTEyYjcwYjU5QHJlcGx5LmdpdGh1Yi5jb20%3D)
Website: https://brokrbindr.com/why-brokrbindr/ (https://link.getmailspring.com/link/1523623624.local-c10bb263-92a8-v1.2.1-7e7447b6@getmailspring.com/3?redirect=https%3A%2F%2Fbrokrbindr.com%2Fwhy-brokrbindr%2F&recipient=cmVwbHkrMDIyMmVhMzdkMjNmZjU4M2NmMDhlZWM5MzZjZmI3MzIzNjJiODViNDlmMmMwNWIzOTJjZjAwMDAwMDAxMTZlODUzNDQ5MmExNjljZTEyYjcwYjU5QHJlcGx5LmdpdGh1Yi5jb20%3D)
