### ISSUE TITLE
Does not list sent texts in chronological order when sent from computer

### ISSUE THREAD

**Issue by johnnyturco** [klinker-apps/messenger-issues#65]
### Does not list sent texts in chronological order when sent from computer

**Device with issue:** MacBook Pro 15 (late 2014) running Windows 10 Enterprise, version 1511; Chrome 52.0.2743.116 m (64-bit)
**Primary device:** Nexus 6P running Android 7.0 (Verizon)
**App version:** 1.1.255
**Steps to reproduce:**

1. Send text from Chrome app or extension (see _Additional information_)

**Additional information:**

If I respond to a text from the Chrome app or extension, it will place the text I respond with _before_ the other person's text. When I respond from my phone it works as expected.

**Comment by klinker41** [comment]
Is your computer's time different than your phones? It will use whatever time your computer says it is and anything sent from your phone will use whatever time your phone says it is.

**Comment by johnnyturco** [comment]
Hi Jacob,

The time is the same on both phone and computer (central time).

Best,

Johnny

**Comment by klinker24** [comment]
How many minutes off are we talking about? If you go into the app, you will be able to see the timestamp of when the message was inserted

**Comment by johnnyturco** [comment]
Jacob,

It's not a matter of minutes off, it just displayed my sent texts above the
other person's. I haven't had the problem since though...

I do have another bug: when I click the notification of a new text on
Windows 10, it opens several tabs with that conversation.

Best,

Johnny

**Comment by klinker41** [comment]
We made a few changes for this, so hopefully you don't see it again.

**Comment by amwmedia** [comment]
I saw this issue myself when my computer's clock was a little off from my phone. Turns out my computer clock was just not syncing with the NIST servers, but I don't think that perfectly synchronized clocks should be a prerequisite for messages appearing in order. Do you think there's a way to order based on a single server time value (or does encryption get in the way of that)?

**Comment by amwmedia** [comment]
BTW, @klinker24 and @klinker41. Thanks for all your hard work! I'm currently previewing Pulse, but liking it so far. :+1:

**Comment by klinker24** [comment]
If I were to re-architect the system, this is something I would change.

**Comment by amwmedia** [comment]
@klinker24 I don't know your exact structure but I'm guessing that encryption is the culprit here. Would it be possible to have each client periodically calculate a clock offset value with the server so that any discrepancies between devices would be removed? You could potentially do this logic against the clock in the master android phone.

Sorry, you probably have more pressing matters to attend to, but it got me thinking. I love problem-solving. :slightly_smiling_face:

**Comment by amwmedia** [comment]
At risk of beating a dead horse...

it just occurred to me that the client may already know the offset if the incoming messages that are being synced from the master Android phone have a time/date stamp and the system uses some sort of real-time protocol like WebSockets.

When the desktop (or any other) client receives a new message, the difference between the received time/date stamp and the client's clock (now) is the differential that we need. This delta takes into account any clock differences as well as network latency. The delta is also cheap to calculate and could be re-evaluated on every newly received message. So long as network latency is relatively constant, this could be used to sync your client clocks (or at least their concept of "now"). Some averaging over time could be used to keep the data more stable during periods of bad connectivity.
