### ISSUE TITLE
Scroll Bar

### ISSUE THREAD

**Issue by JavaCafe01** [klinker-apps/messenger-issues#672]
The scrolling in a conversation view has several issues:

* It's glitchy
* It's too wide
 
Steps to reproduce:
1. Open a conversation window
2. Drag the scroll bar around

Device - OnePlus5

OS - Android 8.1

Pulse - 2.11.1.2072

**Comment by klinker24** [comment]
It is that wide because it is a touch target, it is a quick scroll bar, just like many other apps. That isn't going to change, sorry. What is glitchy about it? It snaps to whatever date you are on. If you have a lot of messages in a conversation, then it will definitely be touchy. Not sure what recommendations you can make to change that.

Here is the dependency I use: https://github.com/turing-tech/MaterialScrollBar

Any issues around this, probably belong on that library, instead of my app. Please feel free to give me more information on the glitchy behavior that you are seeing and I will re-open this. Without more information though, I don't think there is anything actionable for me to do here...
