### ISSUE TITLE
Add support for signal protocol

### ISSUE THREAD

**Issue by jdguffey** [klinker-apps/messenger-issues#686]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Google Pixel <N/A, though, as not an issue>
**Primary device:** Google Pixel on Android 8.1.0 <N/A, though>
**App version:** <N/A, as I don't use the app at the moment>
**Steps to reproduce:**

1. N/A

**Additional information:**

I would love to see this app support the signal protocol (https://www.signal.org/docs/ should provide a reasonable amount of detail if you're unfamiliar with it) integrated into this app. While I am interested in the app, from hearing about it from a friend and seeing a demo of the amazing functionality, I choose not to use any app that doesn't support the signal protocol to enable end-to-end encryption of messages. If you would choose to include this functionality, I would be in your debt and glad to use the app and recommend it to all my security/privacy-conscious friends.

I apologize if I didn't follow the correct process for a feature request rather than an issue. Please feel free to recategorize or browbeat me as you see fit so that this request makes it to the correct place. Also, by all means, if I can be a help in getting this feature off the ground, I would be glad to help however I am able.

**Comment by klinker24** [comment]
Sorry, but I don't see this happening any time soon. Pulse is meant to just be an SMS/MMS app because those protocols are universal. The person you are talking to doesn't have to use Pulse. Signal's protocols are a big shift away from that design and not something that I am ready to get in to, at this point. Obviously I could build signal on top of my current system, but that just isn't something that I am looking to do, right now. Mixing protocols sounds good, but issues will crop up. The folks over there have said that they aren't going to integrate SMS/MMS into their current web system either, for similar reasons.

In the future, hopefully RCS (#143) will be the message-level protocol that is able to bring in more modern features.

Conversations and messages are all end-to-end encrypted on the backend, but it is true that SMS/MMS isn't going to support end-to-end encryption between contacts.
