### ISSUE TITLE
Widget text is unviewable with night mode on

### ISSUE THREAD

**Issue by curtisgroth** [klinker-apps/messenger-issues#699]
**Device with issue:** Samsung Galaxy S6 on Nougat 7.0
**Primary device:** Same as above
**App version:** 3.2.0.2160
**Steps to reproduce:**

1. Enable dark mode automatically
2. View widget. The text color will have updated to white, but the background color will have not updated to black.

**Additional information:**

I am aware that this a small issue but it's been driving me crazy for a while now.

**Possible solution:**

Maybe add a line of code that updates the widget background according to the mode? The text updates fine, so I don't see how that could be a big issue, but I'm not a skilled programmer, so I don't know.

**Comment by klinker24** [comment]
To summarize the real issue here, because it is not as simple as the possible solution suggests haha:

Pulse uses the auto day/night support through `AppCompat`. This allows us to just define two separate sets of resources (a `-night` resource qualifier), and Android will automatically pick which colors to use, based on the time of day.

The issue here is with the refresh rate of the widget data vs the widget background. The data (conversations) are updated much sooner than the widget background. When the data is updated, it will redraw the text, and the text now knows that it is night mode and selects the white color. The background, on the other hand, has no way to update and no way to know that it should change to the dark color. That creates the affect of the white background on the widget, along with the white text. 

I don't know how to fix the root of this issue. This should make it so that the text always uses the same theme as the widget background: https://github.com/klinker41/messenger/commit/fb4bd19211f2ed9d27a00c2676ab8938e1885277

The problem with this solution is that it will not switch to the night mode version of the widget as quickly or as often. It is probably better than seeing a white widget with white text, though.
