### ISSUE TITLE
I wanted to love this app, but....

### ISSUE THREAD

**Issue by fermata49** [klinker-apps/messenger-issues#706]
I replied to a text from my brother this morning using the Pulse desktop app.  This afternoon when I was away from my computer, I looked for a reply on my phone.  My original sms wasn't there.  I did a Force Stop on Pulse and restarted my phone.  Nothing.  

When I came home, I noticed the sms wasn't showing up on the desktop app either, even though that's where I sent it from.  I started to think I must not have sent it.  It also wasn't showing up in the Chrome extension or the web app.  

BUT, if I search for the sms using a keyword I know was in it, all four apps (phone, desktop, extension and web app) find the text.  It was one line so I could see the whole text in all four apps in the search results.  But when I click into into the conversation from the search results, it still isn't there.  

This is one of many headaches with this app.  It's beautiful, but in many ways, it's like a new lover - something you're attracted to at first because of its physical beauty, but then you find out there's some really flaws underneath the surface.  Pulse is gorgeous.  Too bad Mr. Klinker seems to be relying on beauty over quality.

**Comment by klinker24** [comment]
Thanks for the feedback. I will continue to improve the app as it continues to grow. I'm sorry you saw this issue. 

Obviously I don't just care about looks, since there are only a handful of apps that have half of the functionality that pulse does. There are going to be bugs with every single system you use. If I can make the app work for 99% of people, 99% of the time, that is a success on any level, for any type of software. Pulse is the highest rated SMS app on the store, so I do think that this I am well on the way to this goal.

**Comment by klinker24** [comment]
I know very well that Pulse has bugs and acknowledged that in the reply. I thought that was extremely clear.

Unless something is reproducible, it doesn't belong on GitHub, sorry. That is why I definite the template for the issues, that are automatically populated when you create it. A one-off issue isn't something that I can leave open, here. GitHub simply isn't the place for a discussion like this, sorry.
