### ISSUE TITLE
Delete confirmation

### ISSUE THREAD

**Issue by DavidCao22** [klinker-apps/messenger-issues#723]
**Device with issue:** Desktop
**Primary device:** Google Pixel
**App version:** 4.0.1.2180

Can there be a confirmation dialog/pop-up during the message deletion process? In the Android Gmail app there's usually a pop-up that an action was completed (email archived, sent, etc...) as well as an undo button (shown below). In Pulse for Desktop, it's easy to accidentally click the delete button while mousing around. The message is now permanently deleted and the user can't get it back. A confirmation dialog would help prevent users from accidentally performing an irreversible action like deleting a message.

![gmailactionpopup](https://user-images.githubusercontent.com/10539139/43542159-e3cac034-9591-11e8-877b-1333d6bafdb7.png)

**Comment by klorinczi** [comment]
+1 for delete confirmation feature

**Comment by dtron** [comment]
Oh, I just sent an email about this, but it was specifically about the desktop app. I keep accidentally deleting things when I click onto the Pulse application window. Sorry for duplication!

**Comment by el-pyrolad** [comment]
I hardly ever use the desktop app (Windows 10) and today I must have accidentally deleted the texts from my mom (I'm not joking). Over a year's worth of texts, photos of my now-deceased grandpa, etc. that I never imagined would get deleted because I am extremely (extremely!) careful about these things. 

Pulse keeps a backup in the cloud, right? Is there a retention period before my cloud data is gone for good? I am typing this message on my cellphone so obviously my desktop computer synced the text thread deletion with my phone. 

Am I missing anything? Is all hope lost?

**Comment by klinker24** [comment]
When you are viewing the messages on the web or the desktop app, you are directly reading what is stored in the cloud. It mirrors what is on your phone and other devices. Unfortunately if you deleted it, then those messages are not recoverable. The default is to send conversations to the archive. The archive is the trash can.

**Comment by madranet** [comment]
I've just accidentally deleted an entire conversation (on Android) today because I was trying to delete a 'Draft' status  which kept showing as the latest message in that conversation and which wouldn't go away, even though there was no draft message inside the conversation.

Stupidly (yes, user error and all that!) I thought selecting that conversation and tapping the bin icon would either; delete the last message, ask me to select messages for deletion or at least ask me to confirm before doing anything drastic, such as deleting everything.

Instead, the entire conversation was deleted without warning and (as I've subsequently found out) with no way to retrieve that conversation.

That is shockingly bad UI design. You always, always, always ask the user to confirm before committing an irretrievable deletion —especially on a large amount of data. So, I'm curious as to why this has been marked 'Closed' and linked to a Pull Request which is marked as 'Merged'? 

I definitely didn't get asked for any confirmation whatsoever.
