### ISSUE TITLE
No badge notification

### ISSUE THREAD

**Issue by glehenry** [klinker-apps/messenger-issues#739]
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Samsung s8
**Primary device:** Samsung s8 Android 8.0.0
**App version:** 4.0.5.2212
**Steps to reproduce:**
I am using Microsoft launcher
Notification badges are enabled un système settings as well as launcher settings. 
Badge with number of  unread messages never shows

**Comment by klinker24** [comment]
Notification badges are not native to Android. This is the framework that Pulse uses, it has a list of the launchers (mostly third party), that can be supported.

https://github.com/leolin310148/ShortcutBadger

Microsoft would have to add support for my app, rather than me adding support for theirs. This is not something I can control.
