### ISSUE TITLE
Start Desktop App Minimized

### ISSUE THREAD

**Issue by fiver55** [klinker-apps/messenger-issues#744]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Windows desktop
**Primary device:** Android
**App version:** 4.1.0.2236
**Steps to reproduce:**

1.  Launch Pulse Desktop app manually, or have it set to auto start with Windows
2.  Desktop app is opened with window on desktop 

Follow on from issue "Auto-start on login #529"  -- please provide option to start Pulse app minimized to try so there is no need to close it on every reboot / login, etc.

**Possible solution:**

I did try creating a shortcut to launch the app minimized as described in this article, launching from the shortcut app still opens window on desktop 

https://www.cnet.com/how-to/how-to-automatically-start-a-program-minimized-in-windows/https://www.cnet.com/how-to/how-to-automatically-start-a-program-minimized-in-windows/

**Comment by klinker24** [comment]
Sorry, this is not an option that I plan to add directly into the app. I do not believe that this functionality warrants its own setting, since it is so easy to simply close the Window. Having the window be displayed on startup is a verification for the user that I do not want to go away from.

There is a `--no-gui` flag that you can add to the startup arguments, if you are compiling and building the app.

https://github.com/klinker-apps/messenger-issues/issues/708
https://github.com/klinker-apps/messenger-desktop/pull/1

**Comment by DavidUXer** [comment]
I'd love to see this feature added. Seems basic.

**Comment by bniggemyer** [comment]
FWIW, if every application behaved this way, I would have to close about a dozen windows every single time I rebooted.  Seems silly to not give the user an option, and if you believe so strongly it should pop the window just make it be the default and force your grouchy users to go through them menu actions to disable it.  

Anyway I guess I'll just compile it myself.
