### ISSUE TITLE
Would be really awesome if you open source it

### ISSUE THREAD

**Issue by rosenpin** [klinker-apps/messenger-issues#75]
I would love to help developing the client side app for Android!
It looks like it has a huge potential :)

**Comment by klinker24** [comment]
Sorry, I do not think this is likely. We have lots of open source work, but this is not planned to be one of them.

**Comment by JoshuaGarrison27** [comment]
Sorry to comment on a closed ticket, but what about a private repo and make any new developers sign an NDA and NCC of some kind to keep your code secure. The would give you the force of the open source community and their awesome developers/skills but also keep your IP safe. Im not a business guy so I feel sure it is more complex than that. 

Just thought I would offer up the idea since I too found this question because I was wondering the same thing that @rosenpin was. Thanks in advance for any response. Keep up the good work!

**Comment by klinker24** [comment]
I love open source work, which should be evident from my GitHub. 

However, Pulse is an extremely valuable asset for me and isn't something that I am willing to open up at this time. I have many components of Pulse that are open source, but the app itself will not be and I'm not sure why anyone would expect it to be, to be honest... 

There are definite and obvious benefits to open source work, but there are definite and obvious benefits to closed source work as well, which is why 90% of the software you use is closed source.

**Comment by JoshuaGarrison27** [comment]
I agree. Just wanted to open a dialog about it. I appreciate you responding quickly and respectfully.

With that said, I understand your stance on this. To be honest, I think I would do the exact same thing if I were in your shoes. Anyways, thank you for entertaining this question yet again and proving some more insight to your position.
