### ISSUE TITLE
Parameterizable input area

### ISSUE THREAD

**Issue by Jacques57000** [klinker-apps/messenger-issues#762]
**Describe your request:**
I want the possibility to have a parameter to manage the number of lines displayed in the input area of a message. Currently, it is at most 6 lines and I would like to have more (it's better than Android message that has only 4). 

**Describe alternatives you've considered:**
Ideally, the area should expand as needed, without limit.

**Comment by klinker24** [comment]
Unfortunately it cannot expand as needed, due to different screen sizes and configurations. There is a reason that Android Messages only has 4. This is not something trivial to overcome.  There are just some things that I need to make the decision on, this is going to be one of them, this isn't something I want to add a preference for.

With Pulse, I want to avoid just adding preferences that most people will not use or understand. It distracts from the goal of the app, which is to focus on the feature set. There are definitely apps out there that will add infinite settings menus, but that is not what Pulse is going to be.
