### ISSUE TITLE
Forwarding (Web)

### ISSUE THREAD

**Issue by junkbondtrader** [klinker-apps/messenger-issues#765]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues around this behavior.

**Describe your request:**
I don't see the ability to forward an SMS in the web app. I would like to be able to.

**Describe alternatives you've considered:**
Unless I'm missing the feature, there aren't any.

**Additional information:**
I assume that the native app just renders the web app? If not, I would like it there too! 

(Seeing this functionality missing web was enough to make me rediscover that there is a native app so at least that's goodness :smile:)

**Comment by klinker24** [comment]
The web app has the ability to just highlight text and copy it directly. After selecting the text, just press the + button at the top of the screen to select which contact you want to send it to. 

Unless I am missing something, it seems like that is the same process as forwarding a message would be. I don't think that this is something that we need to make additional UI around. The web app is infinitely more capable than the Android app, in this regard. That's why it exists on Android and is unnecessary on the web

**Comment by junkbondtrader** [comment]
I guess. I still think it's missing for continuity of experience between mobile and web - it required you to say that to get me out of the mobile mindset, and I'm no stranger to copy and paste :p That said, certainly unblocks me (though I feel like an idiot, which is a very undesirable design outcome). Totally understand if it isn't worth your dev time though.

**Comment by klinker24** [comment]
I really don't think that design on the web should match that of Android, they are very different platforms with different features and goals. I don't think that having a "mobile mindset" when using a desktop app is really appropriate. That's why we want to use this app on the computer: the computer is more functional and isn't limited by the factors that influence the design of the mobile app.

Know what I mean? This isn't something that I plan to add to the web app, no, sorry

**Comment by junkbondtrader** [comment]
I do, just thought it was worth lobbying for the position. You definitely know Pulse's goals and users better than I do :) Thanks for the consideration.
