### ISSUE TITLE
Multi-select conversation/group customisation and settings

### ISSUE THREAD

**Issue by caruim** [klinker-apps/messenger-issues#774]
Would be great to have the ability to set certain settings and customisations for multiple conversations or groups.

Eg. I have 'work' group and would like for all conversations to be set up with a 5s delay, blue theme, signature and notification sound.

**Comment by klinker24** [comment]
Sorry I really don't see this one coming. It doesn't fit into the way that the themes, and settings currently work. 

* Delays and signatures are on a whole app basis, which isn't something I plan to change. 
* Notifications aren't really going to be able to support this due to the notification channel requirements in Android Oreo and above

The theming would be possible, but that is an additional level of complexity that I decided to go against when I designed for folders system. Initially I planned on theming conversations on a folder basis, which would have been exactly what you asked for here. However, I decided in the interest of keeping it simpler, without just trying to cram thosands of settings down people's throats, I wasn't going to go that route. With Pulse, I want to focus on the feature set, rather than just filling out settings menus. That just isn't the goal of this app.
