### ISSUE TITLE
Color problem, Group Chat

### ISSUE THREAD

**Issue by outahismind** [klinker-apps/messenger-issues#777]
I can't seem to find a similar problem topic yet. I would like to have more customization options for each person in a group chat. I often text the same group of people multiple times a day and rely on their colors to identify them. Sometimes pulse will change these colors for odd reasons and even assign the same color to a couple people. I use the color to identify them and would love to be able to change that.

- [x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [ x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

**Describe your request:**
A clear and concise description of what you would like to see, and why.

**Describe alternatives you've considered:**
A clear and concise description of any alternative solutions or features you've considered. There may already be something that is built into the app, or the platform, that is very similar.

**Additional information:**

**Comment by klinker24** [comment]
If you open an individual conversation with a contact, you can customize the colors that will appear in the group conversation. You don't have to send any messages to the conversation, you can just hit the compose button, start the conversation, then go to the settings page, within that conversation.

**Comment by outahismind** [comment]
I've done that and for certain people in the group chat it won't let me
change their colors. It assigns a different one.

**Comment by klinker24** [comment]
So it works for some people, and not others? If you can give me the steps you have gone through, and how to reproduce this issue, I can look into it further. For example, anything different about those contacts, uninstalling and reinstalling the app, etc.

**Comment by outahismind** [comment]
Sure, I'm currently driving and will be on the road for a few hours. I'll
take some time today to go over everything I've tried to fix this.

**Comment by davidhammaker** [comment]
I am also having this issue.

**Device with issue:** Moto G5+ and Moto G6
**Primary device:** Moto G6 on Android 8.0.0
**App version:** v4.6.3.2390

**Describe the bug:**
In group conversations, one or more contacts (the same contacts each time I open the conversation) will have random colors instead of their assigned colors. At some point, I got a new phone and installed the app fresh, and I still had the same problem in a group conversation with all the same people (though the problem-contact changed). I only see this in group messages, but the "infected" contact will have the random-color problem in multiple different groups. In each instance, I first noticed the problem after joining a large group message (5 or more people).
* e.g. Every time I open a conversation with Adam, Bob, Joe, Kurt, and Maggie, Joe's color is different -- only Joe, every time. In another conversation with just Adam, Bob, and Joe, Joe's color is still randomized every time, even though I have assigned colors in a conversation with just Joe (and his colors are fine in that individual conversation).

**Steps to reproduce:**
1. Join a group message (using 5 or more people).
    * Have someone else start the conversation, where not all the contacts have had colors assigned yet.
2. Make sure everyone in the group sends a message.
3. Open and close the conversation a few times, and check each contact's colors. One or more will likely be randomized each time.
4. Assign colors to each person in the conversation (in individual conversations).
5. Check the conversation again, and see if the colors all match the assigned colors.

**Expected behavior:**
Colors from individual messages should always carry over to group messages.

**Screenshots:**
![screenshot_20190301-121356](https://user-images.githubusercontent.com/41316545/53654663-407a0480-3c1c-11e9-9bbe-1581607f44a1.png)


**Additional information:**
Again, in each instance, I noticed that I joined a conversation that someone else started. I know for certain that I observed the problem with individuals for whom I had not yet picked colors, but I don't know if it works that way every time.

I really like using Pulse, but since the app only really has colors to identify individuals (except for tiny contact names under messages), so I'd love to see this worked out.

Let me know if you need any further information.
