### ISSUE TITLE
MIUI Pocophone F1 on MIUI Global 10.0 notification message issue

### ISSUE THREAD

**Issue by bacevs** [klinker-apps/messenger-issues#778]
**Device with issue:** MIUI Pocophone F1 on MIUI Global 10.0 | Stable 10.0.4.0 
**Primary device:** MIUI Pocophone F1
**App version:** v4.2.1.2280

**Describe the bug:**
The "reply", "call" and "Mark as read" options in the notification drop down cover the message text. 

**Steps to reproduce:**

1. Receive message from Pulse
2. Expand notification 

**Expected behavior:**
The "reply", "call" and "Mark as read" options in the notification drop down should not cover the message text. 

**Screenshots:**
![45344557_1546338585512292_7177139867741061120_n](https://user-images.githubusercontent.com/1433845/47976994-d20fb480-e109-11e8-898b-752a0f7dc985.png)

**Additional information:**
n/a

**Comment by klinker24** [comment]
This isn't something that I will be able to change, unfortunately. I don't control how notifications look, all I can do is tell what the content is. This would be a bug on the Android side. 

You may be able to turn off the "Show conversation history" option in the notification settings section. This would tell Android to use a `BigTextStyle` notification, instead of a `MessagingStyle` notification.

**Comment by bacevs** [comment]
Show conversation history is already disabled.

All other apps like Twitter and stock sms app don't have this issue.

**Comment by klinker24** [comment]
Sorry, I simply cannot control what the notifications look like. I define the style and the content, as stated above, then your device decides how to render them.

https://developer.android.com/guide/topics/ui/notifiers/notifications
https://developer.android.com/training/notify-user/build-notification

This is not something I will be able to change or affect. That just isn't the way that it works.

**Comment by bacevs** [comment]
Yes, sorry it seems the OS was bugging out. My apologies. It's showing up
fine now.
