### ISSUE TITLE
"Mark as read" not working consistently

### ISSUE THREAD

**Issue by kopechcr** [klinker-apps/messenger-issues#792]
**Device with issue:** Pixel 3 on Google Fi, Android 9 with November 2108 security patch
**Primary device:** above
**App version:** 4.2.3.2288

**Describe the bug:**
"Mark as read" on notification pulldown has no effect on message status in the notification bar, or in the app itself. This is usually after I have replied to a text using the in-notification reply feature. The conversation will not clear, not will it if I hit "Mark as read" as expected.

**Expected behavior:**
Mark as read clears the conversation notification and marks the convo as read within the app

**Comment by klinker24** [comment]
It happens every time you reply to a text from the notification. The action itself will work fine (the call will go through, the conversation is marked as read, etc), the notification just refuses to clear. I don't know why. I have looked into it, even using `NotificationManager.cancelAll()` does not cancel this notification.

Android Messages seems to do it some how, but it simply will not dismiss the notifications for Pulse. It seems like Android might be disallowing it, because the notification is recreated via the system (instead of Pulse), after replying. That doesn't explain how Android Messages gets around it though.

It seems to me that this is something that Google is explicitly preventing. Signal had the same issue opened, and they closed the ticket:

https://github.com/signalapp/Signal-Android/issues/8194

I feel as though I am going to do the same here. I don't know how Android Messages does it differently, but Android is simply not allowing my app to cancel the notification, after a reply has happened.

I wouldn't say that this is working as expected, nor is it fixed. If any of this changes in the future, I will re-open this ticket. At this point though, I don't have anything actionable, here.
