### ISSUE TITLE
Option to show folders in conversation list

### ISSUE THREAD

**Issue by abhubbart** [klinker-apps/messenger-issues#813]
Would be cool to have an option to have folders appear in the conversation list. Once clicking on a folder, it would take you to the existing folder view.

**Comment by abhubbart** [comment]
Also, conversations in a folder would be removed from the main conversation list

**Comment by abhubbart** [comment]
I understand what you are saying, however, would really appreciate is as a
configurable option, not the default or only option.  Just a checkbox in
the options.

Just a thought.

**Comment by klinker24** [comment]
I really want to stay away from creating little tweak options like this. I have discussed this in the past, but I don't want Pulse to turn into an app with unlimited settings or configurations. That just isn't the goal. I want to focus on features, rather than tweaks, and that means there are some things that I just need to make the decision on. 

I know that that isn't what everyone wants. Some people love apps that let them tweak everything. From a growth standpoint though, limiting this is a better decision. I have made Talon for Twitter and EvolveSMS, both of which have insane settings menus, both of which are completely overwhelming, and both of which pale in comparison to the success of Pulse. Every setting that I add to the app is going to mean a larger overhead for new users and frustration for current users trying to find/understand the settings they use.

Sorry I think that this is something I won't be able to add to the app
