### ISSUE TITLE
Global notifications

### ISSUE THREAD

**Issue by sherweed** [klinker-apps/messenger-issues#817]
I have set the ringtone for global notifications. However, when I look at the settings for every conversation for which I have not set a custom ringtone, the ringtone is set to the default system notification, not the ringtone I selected.

**Comment by klinker24** [comment]
Please open a new issue and fill in the template so that I have details on your device. Notifications are heavily dependent on your version of Android.

**Comment by sherweed** [comment]
I tried opening a new issue but I don’t see a template. 

Here is the info on my phone:

Galaxy S9 Model # SM-G960U
Baseband = G960USQS3BRK2
Kernel version 4.9.65
Build # R16NW.G960USQS3BRK2


Please let me know if there is any other info you need.

Thanks

Ken

**Comment by klinker24** [comment]
Please see the topic on notification channels on my help page

https://messenger.klinkerapps.com/help

Notifications will use the "default conversation notifications" channel until you click the preference within that conversation's settings to customize the notifications. With 8.0 and above, all notification customization is done through the system. I will not be able to affect it in my app.

The issue template is generated when you select "bug report" or "feature request", when creating a new issue.

**Comment by sherweed** [comment]
It's not using the default "conversation" notification. It's using the default "system" notification. This is a deal breaker for me and I'm still in the first 7 days of using the app. If this can't be fixed, I'll be requesting a refund

**Comment by klinker24** [comment]
Sorry I don't think you understood what I meant or looked through that help page topic. Please see the topic on notification channels on my help page, for more information on this system and how you can customize the notifications within Pulse, on a global and per-conversation basis.

**Comment by sherweed** [comment]
I understand AND followed your instructions to look at the notification channels the on your help page. I followed those instructions (which I had already done before I contacted you for help) so, maybe I'm not clearly explaining the problem: when I go into the alerts/notifications channel, it allows me to pick the sound that I want to use for uncustomized conversations. The problem is that it is not actually using/applying the sound I have chosen. Instead, when I receive a message in any uncustomized conversation, it uses the default system sound. I have gone into the customization settings for those conversations and it shows that the sound bring used is the default system sound, not the sound I have chosen through the alert settings.

**Comment by klinker24** [comment]
When you go into a conversation's settings menu and select the option to customize the notifications, you are creating a new notification channel, for that conversation. It will no longer use the preferences you selected for the "default conversation notifications" channel. 

To restore that conversation to the default channel, simply use the other preference in the conversation's settings menu: "restore default notification settings".

**Comment by sherweed** [comment]
That didn't work. It also doesn't address the root problem which is that the notification defaults to the system sound (not the sound I selected in the app settings) when any new (and therefore uncustomized) conversation begins.

**Comment by klinker24** [comment]
I cannot change the notification sound that a new notification channel defaults to, sorry. 

If a notification channel does not exist for a conversation, it will use the default channel as we have discussed. Every single time you go to the notification customization preference within a setting, it will create the channel for that conversation. Do not go there and do not use that preference if you want to use the default channel. It works as I am describing. 

You can long click any notification to access the channel that posted it. If it goes to the custom channel instead of the default conversation notifications channel, you have created the custom channel for that conversation. Do not create the custom channel if you want it to use the default settings. 

I am not sure what else I can say about that, or how to phrase that any differently, sorry. These are system level settings now, outside of Pulse's control.
