### ISSUE TITLE
Contact's avatars not showing up

### ISSUE THREAD

**Issue by bobxenon** [klinker-apps/messenger-issues#819]
Hello,
I am using a huawei phone, and some of the contact's avatars in the main list of conversations do not show up, as seen on this screenshot.
https://drive.google.com/file/d/1MbfET3pJcMcsNEKEWd0C9azjy0ODIEre/view?usp=drivesdk

I don't see why this happens, as it did not happen on my previous phones, wiko and samsung.

**Comment by klinker24** [comment]
If they aren't showing up, then your Contacts app is not allowing Pulse to access them. This would be a device issue, based on the permissions, I will not be able to change it.

It would be mitigated with #133.

**Comment by bobxenon** [comment]
Oh thank you. I did not see what it had to do with #133, but i guess you're saying it will be fixed with custom icons.
Sorry if I wasted your time. :(

**Comment by 0kommanix** [comment]
I have kind of a similar issue as my contact avatars are missing as well. They however are all displaying correctly on the first import and stay for some hours/days before they all vanish and only the default avatar is displaying. Clearing cache doesn't fix the issue but clearing data does (triggers import). However this requires setup again and because there is no backup/restore of settings this is not really an option. Really a bummer and close to switching because it makes finding conversations in the conversation list a tough endeavor.

If this can't be fixed, can we force a re-import of messages/avatars without requiring the whole setup procedure?

**Comment by 0kommanix** [comment]
OK, the contact images lasted for about a week and have vanished again from the conversation view. Only clearing app data and reimporting the messages gets the contact images back. Without images I find it really hard to identify conversations so unfortunately I need to look for another messaging app until this gets fixed.
