### ISSUE TITLE
Please expand Web search & Display depth for further consideration

### ISSUE THREAD

**Issue by isjac777** [klinker-apps/messenger-issues#835]
I understand #343 (related but not the same) is about speed and privacy BUT I'm not asking for Android level search just extension of what is currently supported. 4x the number of messages to display, expanding upon scroll or clickable link "see more messages". 

The current quota for the number of viewable and searchable messages is too limited. Please expand this by default or enable the ability to expand it within app settings.

mySMS supports much deeper search but I understand it's probably not on the same architecture and that it might not be feasible (or desirable) in this extent with the Pulse system.

I am often unable to find message threads only a few days old, can this can be expanded in some way, even to some extent?

Thanks for your development of this App! Lifetime member here that would consider an upgrade pack for this feature.

**Comment by klinker24** [comment]
Sorry, the search will not be able to be expanded. MySMS does not use end to end encryption, so it is not the same situation at all. The topic you have references directly states how the search works and why searching message content will not be possible. It searches conversation titles and snippets.

If you need search, it will have to be on the Android app. I am not going to compromise security and privacy for a single feature. This is not something that will be able to change.

**Comment by isjac777** [comment]
Okay, I think I understand. You are at the limit of what is possible for
encryption?

Thanks for your consideration,
Isaac

**Comment by klinker24** [comment]
Due to the encryption, the search has to be done locally, after messages are downloaded and decrypted. I cannot download all of your messages and decrypt them locally, that would be impossible due to time constraints. These constraints are already discussed and analyzed, in detail, in the topic that you have already linked to.

A system without end to end encryption could search against the database and return only the relevant results. Pulse cannot.
