### ISSUE TITLE
Ability to send empty sms

### ISSUE THREAD

**Issue by Tomatoide** [klinker-apps/messenger-issues#861]
**Describe your request:**
For some carriers, the ability to send empty sms is required for subscribing to some services.

**Describe alternatives you've considered:**
Using another app (usually shady apps on play store) to achieve this basic functionality, or built in sms app (usually it workes by putting a space then you can send it).

**Comment by klinker24** [comment]
Can you give me an example of a service that requires this? Honestly, I don't really understand the use case. Why would a service require you to send an empty SMS, almost no SMS apps would do that for you. That just doesn't make sense to me. Why not just type a random letter if sending an SMS to this number is the requirement?

If it is a carrier thing, why would your carrier require you to put an empty space into the stock SMS app? It sounds like you are saying that your carrier doesn't even allow you to subscribe to these services, out of the box.

I am very hesitant to add something like that. You could accidentally hit the send button at any time, and Pulse would just randomly send empty messages. That just doesn't seem like a feature that a messaging app should ever have.

**Comment by Tomatoide** [comment]
Well, ask our stupid carriers we have over here :D 
Some mobile internet packages for example have a specific number for each different package that you send an empty sms to in order to subcribe, some special offers or free stuff and whatnot, they tell you send an empty message to x number to activate this offer... It's annoying and idiotic I know but this is unfortunately what we have to deal with here.. not all users are from north america you know :)

**Comment by Tomatoide** [comment]
If you are afraid of accidental hits on the send button and sending empty messages, may be put it as an option in a dropdown menu for example

**Comment by klinker24** [comment]
To be honest, I don't really want to add this into Pulse. While I understand that not everyone is from North America, geography doesn't play a role in this. That is just a weird, one-off feature, that would just distract and infuriate 99% of users... I am going to recommend that if you need to send one of these messages, you can do so from the stock app on your phone.

With Pulse, I don't want to add options into the app that people will not understand or will not want to use. The small percentage of people that need to use this (and it must be very small, since you are the first of millions of users to ask for it) does not warrant a new settings toggle or option in the overflow menu. 

In the past, I have filled my apps with every little tweak option that anyone has ever asked for. In the end, Pulse's generalized settings have been orders of magnitude more success. More settings ultimately just means a larger overhead for new users and a more confusing experience for existing users. I have never seen a messaging app that has a setting for this, so it really isn't something that I feel should be included in mine

**Comment by Tomatoide** [comment]
Well I thought that enabling that I send a message that has just a space would be an easy implentation...

**Comment by klinker24** [comment]
As I noted above, my objections are based on reasons other than difficulty.
