### ISSUE TITLE
The same apple contact groups are divided on 2 or 3 groupes on Pulse

### ISSUE THREAD

**Issue by xavierdes** [klinker-apps/messenger-issues#871]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Ex: MacBook Pro on MacOS 10.12, running Chrome v54
**Primary device:** Ex: Pixel XL on Android 9
**App version:** Ex: v4.1.5

**Describe the bug:**

**Steps to reproduce:**

`... more steps`

**Expected behavior:**

**Screenshots:**

**Additional information:**
Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by xavierdes** [comment]
When sync Pulse from Smartphone (samsung) to MacBook.
Some on my contact groups are divided on 2 or 3 groups with the same name.
And some of the groups are missing.
I re-sync, but it makes exactly the same trubles. 
Thanks
Xavier

**Comment by klinker24** [comment]
Pulse is going to import conversations in whatever order and grouping that your previous app had written them into the shared database. Sorry, but I don't understand what you mean or the issue you are having. Pulse does not manage your contact groups either. It just displays whatever groups your contacts app provides.

Without more information, a more detailed description of your issue, some screenshots, or some steps to reproduce this, I will not be able to do anything more with this and it will need to be closed. The template was there, so that it could be filled in, not just posted as-is. Please provide more detail, following the template, then I will re-open this issue.

**Comment by xavierdes** [comment]
Well !!!
How to tell you it more simple ?

I had groups contact in my Apple, and in my phone, they both sync very well since years.


But…

When I use Pulse to write a message to one of these groups,
1) I discover that Pulse show 2 or 3 groups with the same name where I had just one !
Here I send you screenshots of Pulse showing 2 groups called « drome » where it was just ONE in my Apple/Contacts and in my smartphone

2) some of my previous groups don’t appear in Pulse
I send you screenshots of
- Pulse which doesn’t find my group « perso »
- a view of my  Apple/Contacts app where you can see the groups « drome » and « perso », as exemple.  

Best regards

Xavier
