### ISSUE TITLE
Voice and Video Calling

### ISSUE THREAD

**Issue by cdcv** [klinker-apps/messenger-issues#876]
The title says it all: add voice and video calling (like WhatsApp, Skype, Hangouts, etc)... and this app will be the best communication app in the world across functions.  Period.

Using webRTC infrastructure, creating an audio and video calling app today is actually surprisingly easy (I have done it myself).  If you want to try building a quick working audio/video-calling prototype (eg in <1 day) look a the amazing webRTC tools and working demos provided by  https://www.webrtc-experiment.com/.

If you need further resources (incredible what you've done as a single individual)... get them.  Get some co-founders or raise some money.  That said, based on what you've already done, I don't actually think that adding calling functionality is beyond you.  Try creating a beta!

I think that the Pulse app is amazing and have already started recommending it.  It solves a huge problem faced by millions of people... the lack of a good-quality, cross-platform, SMS-based messaging app.  It is potentially a category-killer at a time when many people are wanting to get away from things like WhatsApp (due to privacy and other issues).  

See next feature request: secure messaging.

Thank you for creating this.  The world needs it.

- [x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [ x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

**Describe your request:**
A clear and concise description of what you would like to see, and why.

**Describe alternatives you've considered:**
A clear and concise description of any alternative solutions or features you've considered. There may already be something that is built into the app, or the platform, that is very similar.

**Additional information:**

**Comment by klinker24** [comment]
Sorry, but this is not something that I currently plan to add into Pulse. Pulse is a messaging app, focusing on text communication. Adding this into Pulse would pivot from my app and development focus, which is not something that I am really excited to do. 

The whole point of Pulse, and why I use SMS, is that you can talk to anyone, who is on any platform, who is using any other app. SMS is universal, which is why it has remained popular. I really don't want to get away from that idea of universality. All of the apps that you referenced are proprietary protocols, forcing the users to be in their ecosystem. While I don't think that there is anything wrong with that, it isn't the goal that I am working towards.
