### ISSUE TITLE
Ok Google, read my texts

### ISSUE THREAD

**Issue by fastoy** [klinker-apps/messenger-issues#878]
Our state has a new law going into effect July 1 that requires handsfree operation of smartphones. How can I use Google Assistant ("OK, Google") to read incoming Pulse SMS messages?

**Comment by klinker24** [comment]
At this point, Google assistant isn't going to be able to do anything like that through Pulse. Everything in Pulse is end to end encrypted, and an assistant action cannot decrypt them. Pulse has no way to provide content to the assistant.

On your phone, the Google assistant wouldn't need Pulse to read messages, but this is something that Google would need to make. It could read messages from the internal database on your phone.. The assistant could also just read the notification content, but again, that isn't something that I can add to the assistant. 

Unfortunately, there isn't really anything that I can add around the assistant, because of the way Pulse accounts have been designed.
