### ISSUE TITLE
Auto-update renders Pulse unusable

### ISSUE THREAD

**Issue by ichisaur** [klinker-apps/messenger-issues#881]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Surface Book (original) running Windows 10 Pro with Native Desktop App
**Primary device:** Galaxy S7 Edge
**App version:** v3.4.2 through 3.4.5

**Describe the bug:**
When updating Pulse through the native desktop app's updater prompt, the installation process will appear to begin and install the app, with the progress bar filling up. Once this is done, the installation window disappears and nothing takes its place. At this point, Pulse will refuse to start up. Clicking on any shortcuts made for the app does nothing. It does not appear in windows task manager either. Only solution is to restart the computer, delete all Pulse related files from .appdata, and reinstall the newest version of Pulse

**Steps to reproduce:**

1. Autoupdate prompt appears
2. Click on 'update'
3. Wait for update to complete
4. Pulse now refuses to run

**Expected behavior:**
Clicking update on the update prompt installs the new version of Pulse and it opens up after installing app.

**Comment by klinker24** [comment]
I hadn't heard of any issues around this. It had happened in the past too? Pulse just uses the update system built in to `electron-builder`, so I am not really sure if there is anything I can change. I know that it isn't failing for all devices, because it updated just fine on my two Windows machines

**Comment by ichisaur** [comment]
Its been going on for a while. I do believe there was a period where auto-update worked but I can't be certain.

**Comment by klinker24** [comment]
If you could tell me what version it was working on, that would be helpful. Otherwise, I am not sure I am going to be able to do anything here. There are a ton of different reports for the auto updater in electron https://github.com/electron-userland/electron-builder/issues?page=1&q=is%3Aissue+is%3Aopen+windows+update&utf8=%E2%9C%93

**Comment by klinker24** [comment]
I am going to close this as an upstream issue. If you have more information in the future, feel free to post back here and I can re-open or explore further.
