### ISSUE TITLE
Disable fingerprint for security and only use passcode

### ISSUE THREAD

**Issue by bostongreekgeek** [klinker-apps/messenger-issues#886]
- [ x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

**Describe your request:**
An option that allows you to disable the fingerprint login to private messages and having to use the passcode.

**Describe alternatives you've considered:**
You could disable fingerprint options globally on the phone so that doesn't come up in the app, but that disables it everywhere.

**Additional information:**
Fingerprint security is convenient but not secure as this could be done without your consent either while you are awake, or sleeping or even possible to spoof someone's fingerprint (unlikely but possible).
It's nice as an extra option for convenience but you often want to disable it in certain apps.

**Comment by klinker24** [comment]
Sorry, but this isn't something that I plan to add. Your reasoning for it is that it isn't as secure, but that applies to the entire phone, not just my app. If you want to disable it within Pulse, you will need to go through the system level settings. Pulse is going to use the same level of security as you have on the rest of your device

**Comment by bostongreekgeek** [comment]
Yes it does apply to the entire phone..thats the point, but you leave
fingerprint on for convenience so if you lost your phone someone couldnt
get in to certain things but when its with you..it doesnt matter as much.

And yet several apps have the option to disable the fingerprint option so
you can still use it for convenience everywhere else but leave it for
convenience where you want it. You do realize that the fingerprint login
for security is pointless?

A simple scenario for your privacy rights for example is that if you are
being detained, your phone can be unlocked with your fingerprint without
your permission but a warrant is needed to use a passcode. Did you know
about this? It is not only that it is less secure.

But hey, close the request without even considering how important this
request is. Makes sense!

I didnt think a developer of an app would be so close-minded and
immediately dismiss something like this.

**Comment by klinker24** [comment]
It seems to me that if you are being detained, you would want your entire phone to only be accessible by a warrant, not just a single app. If you are worried about this in one app, I don't see why you would want them accessing your other apps, such as email, social media, and every other app that contains private information. 

If the authorities wanted to get at your messaging history, they could go through your carrier. They don't need to be able to unlock your phone or go through you at all, if they want that information.

I don't want to add options to my app, just to have them. They should be there for a reason and not confuse people. If you have fingerprint set up for the rest of the phone, it would make sense that a user would expect to use that within all of their apps. I am sure that there are apps that allow you to choose this, but that doesn't mean that it is the right approach for the majority of people.

Clearly I did consider your request, both when you emailed it and when you posted it. Do not assume otherwise. I have just as many reasons as you have for this option, going against it.

**Comment by bostongreekgeek** [comment]
that is just an example..and clearly you did not consider it

**Comment by klinker24** [comment]
Since I was immediately able to tear-down that use-case for this request, it seems as though I have considered it. I provided multiple examples for why your use-case just does not make sense.

I am sorry, but this is not something that I plan to add into my app. You have full control over this already, at the system level. It is not something that a messaging app needs to have.
