### ISSUE TITLE
Can't buy the lifetime purchase

### ISSUE THREAD

**Issue by TheClarkeAsylum** [klinker-apps/messenger-issues#899]
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ ] I have verified that this is something that is reproducible.

**Device with issue:**  Samsung S8
**Primary device:** Samsung S8
**App version:** 4.11.2.2553

**Describe the bug:**
I've been trying to buy the lifetime purchase on my android phone over the past few days. If I click to subscribe to the lower levels, I get the android payment screen, but if I click the lifetime payment I just go back to the menu. 

**Steps to reproduce:**

1. Go to the purchase screen
2. Click to buy lifetime purchase
3. Get returned to the previous menu

**Expected behavior:**
I hoped to be able to buy the lifetime purchase so I can use my account across various platforms

**Additional information:**
I haven't tried to buy it on other platforms because I have credit on the android store wo wanted to use that towards the purchase of Pulse.

**Comment by klinker24** [comment]
You will need to send me an email about this. It isn't something that I will troubleshoot over GitHub, because I will need personal details such as your email address.

I have been getting lifetime purchases all morning already, there doesn't appear to be any configuration issues on my end. The purchases are something that you set up once with Google, and I have had them set up successfully for almost 3 years now. I would probably recommend just restarting your phone, or reinstalling the app. All purchases and the purchase flow is managed completely by Google.

If neither of those work, please send me an email and I can see if Google is reporting any issues or has any reasons to block you from making the purchase.

luke@klinkerapps.com
