### ISSUE TITLE
Add subscription payment structure

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#9]
**Information:**

To make some money that will pay for server costs, we should implement some type of payment structure (not much since subscriptions tend to scare people off!).

Most of this will need to be implemented in the app side of things, but the server should store this data and keep track of it so we know when user's are expiring.

We could do something like:
$0.99 / month
$1.99 / 3 months
$5.99 / year

Then, a $10.99 "Lifetime" subscription as a one time payment.

Todo:
- [x] **Play Store:** Set up subscriptions.. These work on an auto-repay system, so unless the user specifically cancels them, it will pay every month.
- [x] **Backend:** Add the `subscription_type` and `subscription_expiration_date` to the `account` table.
- [x] **Backend:** Make route to update the expiration date and push it down to devices with a fcm message.
- [x] **Backend/Web:** make an admin controller route to display the subscription status of a user
- [x] **Backend/Web:** make an admin controller route to update the subscription status of a user
- [x] **Android:** Set up the `Account` to hold subscription information and make sure we get FCM messages for the changes
- [x] **Android:** Set up `Retrofit` to use the new APIs
- [x] **Android Primary Device:** Set up the account with an initial `trial` flag.
- [x] **Android Primary Device:** Set up the payment flow.
- [x] **Android Primary Device:** Make a service that will run at that expiration date, if it detects they have cancelled the subscription, the app will log them out automatically.
- [x] **Android Primary Device:** Inform the user if they have been logged out (could be via notification or a dialog when they return to the app)
- [x] **Android Primary Device:** Update the `subscription_expiration_date` after subscription refreshes
- [x] **Android Primary Device:** What happens if they log into an expired account?
- [x] **Android Primary Device:** Add the ability to change the subscription type from the "My Account" page. Should just sign up for a new subscription, then tell the user they can cancel the old one.
- [x] **Android Primary Device:** Migrate current beta testers (that have signed up for an account) to a trial. Be sure to alert them that this has happened.
- [x] **Android Primary Device:** Check the subscription status in the signout and subscription check services.
- [x] **Android:** Improve UI for purchases
- [x] **Android:** Put account type on the my account fragment
- [x] **Android:** Notification for when an admin manually upgrades a users account
- [x] **Testing:** ensure the subscriptions are working with an alpha build on Hannah's phone

Notes: 
- `subscription_type` could be of types `trial`, `subscriber`, and `lifetime`. I don't particularly want a lifetime membership for users, but it would be helpful for us.

**Comment by klinker24** [comment]
With this, I would like to change the onboarding as well. I don't think it is a good idea to push a subscription on them before they have even opened or tried the app. So I want to change the onboarding to just display the features, then go right into the initial data load (without creating an account).

This will include a number of changes to the Android signup flow:

- [ ] Remove the subscription information from the initial onboarding.

This onboarding activity should have the two pages already available (Messenger Intro and Message Anywhere), a page about customization on a per contact basis (with the person icon from Plaid), and a page about pinned conversations.

The user should have the skip button enabled if they don't want to go through this.

After the initial onboarding, it will go directly to loading your messages into the app.

- [ ] Change the "My Account" section in the drawer to "Text from any Device" and change the icon to the multi device icon
- [ ] Clicking the "Setup Account" button on that "My Account" page should display another onboarding style `ViewPager`. This one will start with introducing all the different devices it works on, then the last page will have the payment information. The last page will have buttons that say "No Thanks" or "Sign up!"

Pressing the "Sign Up!" button will take them to the login page where they can create an account or login to an existing account. If the user chooses to log in, I should ensure that the initially loaded messages are removed from the database and the messages are brought down from the cloud instead.

Pressing the "No Thanks" button should take them back to the conversation list. Next time they hit "Setup Account", it should launch this same onboarding page again.

- [ ] We should alert them to this functionality (that they can do the cross device messaging) after a few weeks of using the app. It should just launch the same "Setup Account" `ViewPager`.

**Comment by klinker41** [comment]
I think that one thing you'll want to keep in mind is that any device that doesn't have texting capabilities should go directly to the login page. However, not showing the user's a sign up screen on the phone initially will confuse users who want to go right into texting from their tablets but don't know how to make an account on a primary device.

**Comment by klinker41** [comment]
We'll also have to add some functionality to the admin console to manually manage subscriptions for different users. For example, setting their account to a lifetime membership or extending their free trial another week on request, those types of things.

**Comment by klinker24** [comment]
I think that the questions in your first point should be handled.

**Web:** earlier today i added text to the login screen saying that you MUST sign up through the phone app.
**Tablet:** The tablet has always skipped the initial onboarding and gone directly to the sign in screen, which says that you need to sign up on your phone first. No changes should be made here.
**TV/Wear:** Since they go through the web activation, the user will see on the web sign in screen that they must sign up through their phones first.


I think I will try to add a bit more separation and visibility to the "My Account"/"Text from any Device" section in the drawer. Will put it in its own section at least, with a divider.

**Comment by klinker24** [comment]
Create subscription migration: https://github.com/klinker41/messenger-server/commit/54e24cd31277bf62a15ef2c41fa898c7e2b86f4f
Routes for updating subscriptions: https://github.com/klinker41/messenger-server/commit/e61f907de2b7b198947ee233aca2016f5442bbe9
Routes for controlling the subscription system from the admin page: https://github.com/klinker41/messenger-server/commit/c77838909a53488a6557d62f30871b80c0b3fbf5

Update the admin page to manage subscriptions: https://github.com/klinker41/messenger-web/commit/7e6791737b674d1b04b1a930a0c5d4f31febef2f

**Comment by klinker24** [comment]
Update account subscription info on android: https://github.com/klinker41/messenger/commit/68636678d53a23f8de1eb288a8a4e0929cae9ecc

**Comment by klinker24** [comment]
I have almost all the frameworks for this structure set up in the app. Now just have to actually implement the in app billing

**Comment by klinker24** [comment]
I have added notes to the wiki about how the subscription flow should be managed: https://github.com/klinker41/messenger-server/wiki/Subscription-Flow

**Comment by klinker24** [comment]
The sign out and expiration check methods should now be complete, along with the purchase flow for signing up new users.

The last things are to improve the UI for the purchases and to migrate beta testers into the trial period.

**Comment by klinker24** [comment]
Ok this is a sanity check for me to make sure I have done everything I can think of.

**New Users**
- [ ] Open the app, go through initial onboarding, then load conversations into app
- [ ] Select "Text from Anywhere" in drawer and see the billing onboarding.
- [ ] Selecting "No thanks" sends them back to the conversation list, they will see the onboarding again if they hit that first item
- [ ] Selecting "Start trial" automatically opens up the purchase selection dialog.
- [ ] It is explained to them that they will not be charged for 7 days and can cancel at any time
- [ ] The lifetime subscriber option informs them that it is a one time payment
- [ ] If they quit the purchase selection dialog, it should come back if they select the "signup" preference
- [ ] If they select an option to purchase, but then cancel the purchase, the same thing happens as above.
- [ ] If they select an option to purchase and go through with the purchase, allow them to create an account

** Creating an account:**
- [ ] After creation, ensure the subscription checker runs in 7 days.
- [ ] Ensure the `TRIAL` flag is written to their account (even if they select lifetime)

**Signing into an old account:**
- [ ] schedule the subscription check service at their account timeout, if their account timeout was before now, then write their account timeout to the subscription type's timeout

**Subscription Check Service:**
- [ ] query to see if they have purchases
- [ ] If they are `LIFETIME`, make sure the subscription check service sees that when it goes off and immediately stops checking the subscription status and doesn't schedule another one. 
- [ ] If they are `LIFETIME`, write that to the account, so that the subscription checker stops going off
- [ ] If their account is current, with no expiration, write the next expiration date to their account and ensure it is turned to `SUBSCRIBER`.
- [ ] If their account is not current, has expired, then give them the expired notification and schedule the sign out service to run in 2 days.

**Sign Out Service:**
- [ ] query to see if they have purchases
- [ ] If they are `LIFETIME`, make sure the subscription check service sees that when it goes off and immediately stops checking the subscription status and doesn't schedule another one. 
- [ ] If they are `LIFETIME`, write that to the account, so that the subscription checker stops going off
- [ ] If they have purchases, DON'T sign them out. Write the new expiration date to their account and turn it to `SUBSCRIBER`.
- [ ] If they don't have a purchase, delete the account on the device and cloud.
- [ ] stop scheduling the sign out service, because they will have either been forcefully signed out or they will have a new purchase written to their account.

**Changing an account from the admin console:**
- [ ] User's primary device should receive the changed FCM notification
- [ ] If they are moved to lifetime, cancel the subscription check service.
- [ ] if their subscription has been updated, then write the updated timeout to their account and schedule the subscription check service.

**Comment by klinker24** [comment]
![screenshot_20161101-205700](https://cloud.githubusercontent.com/assets/4874287/19914098/e00c11a4-a075-11e6-8263-09724e2e7f3d.png)

This purchase system was probably one of the slowest/most frustrating things I have ever made, but it works well, ready for prod :) last thing is giving the ability to change their purchase

**Comment by klinker24** [comment]
Extremely happy to get to close this right now :)
