### ISSUE TITLE
Mute conversations by default

### ISSUE THREAD

**Issue by midenok** [klinker-apps/messenger-issues#906]
Please add configuration setting for creating new conversations muted. I always mute all conversations except several from known contacts. It would be good to have 3 values for this option, new conversations:

* always muted;
* muted if not in contacts;
* always unmuted.

**Comment by klinker24** [comment]
I really am not sure if this is something that I would be interested in adding or not, sorry. The mutes are designed to be a blacklist of specific apps, rather than a whitelist. Less than 1% of Pulse's users have ever even muted a conversation, which is what makes me hesitate. I don't want to add an option, just to add it. I want to make sure it is useful for everyone and that what it does is easily understandable.

While I can see why you would want something like this, the stats above tell me that this is probably not something that more than a handful of people would find useful. People like to be notified of their messages, regardless of if it is someone that they know or not. 

If you are on Android 8.0+, you could actually accomplish this already, through the notification channels. You would need to disable the notifications for the "default conversation notifications" channel, then create channels for each of the conversations that you want notifications for. 

https://messenger.klinkerapps.com/help

I think that that system level functionality is going to be as far as I take this one, sorry. I do not think that this is something that I am going to include directly in Pulse, but you can already accomplish what you are looking to do, in a few steps, outside of the app.
