### ISSUE TITLE
Apply Day/Night Auto Theming at User-Specified Hours

### ISSUE THREAD

**Issue by UnkeptFir** [klinker-apps/messenger-issues#926]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

**Describe your request:**
I think a user-specified time for turning on/off night mode would be a beneficial add to the Android app. During times of the year or different geographies where the sun may, for example, set at 6PM or rise at 7AM, the default 8PM-6AM schedule includes hours where the "day" theme overlaps with actual night time. 

**Describe alternatives you've considered:**
- Setting the theme manually; benefit of auto day/night mode is lost
- Auto theme based on sunset/sunrise - would require location access, which may not de desired by all

**Comment by wizard7926** [comment]
I second this. 

On Android 10, this has defaulted to only going into dark mode when the system is set to Dark theme, which I never use. 

On Android 9, Pulse would switch to dark mode any time my phone had Night Light mode turned on, which makes much more sense to me.

**Comment by klinker24** [comment]
On Android 10, Google recommends three choices for theme:

`System default` (following the device's theme selection)
`Always light`
`Always dark`

Pulse also adds a fourth (`always black`) option, since it has an all black theme. Pulse is going to stick with the rest of the device on Android 10, it isn't going to continue to have the legacy day/night option that older versions of Android have had.

https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

--- 

As for user specified hours, I do not see this change coming, since Android is moving away from that direction, sorry. With the introduction of system wide theming, Pulse should support it however Google recommends, as it does not. Obviously not all devices are on Android 10, but I already have around 15% of my userbase on it, and it is growing rapidly. Unfortunately, it does not make any sense for me to make changes around a legacy method at this point in time, when no modern versions of Android will be able to support this new feature.
